const clusterLabels = {
  0: 'narration/account',
  1: '',
  2: 'private discussion',
  3: 'assignment',
  4: 'charge',
  5: 'appraisal',
  6: 'questioning',
  7: '',
  8: 'disputation',
  9: '',
  10: '',
  11: 'organizing',
  12: 'judicial examination',
  13: '',
  14: 'presumptive interaction',
  15: '',
  16: '',
  17: 'public spectacle/novelty',
  18: '',
  19: '',
  20: '',
  21: '',
  22: '',
  23: 'conflict',
  24: 'oration',
  25: '',
  26: '',
  27: '',
  28: 'argument',
  29: '',
};

export default clusterLabels;
