export const systemGroups = {
  moveSystems: ['move_recursion'],

  actSystems: [
    'act_tentativeness',
    'act_recursion',
    'act_progression',
    'act_type',
    'act_sequencing',
    'direction',
    'contemplation',
    'conventionality',
    'orientation',
    'interjection',
    'expectation',
    'question_type',
    'yes_no_type',
    'bias_type',
  ],

  discourseSystems: [
    'discourse_marker_type',
    'ostentation',
    'direct_address',
    'proposition_marking',
    'operator_as_marker_type',
  ],

  otherSystems: [
    'combination_type',
    'speech_centrality',
    'instantiator_expression',
    'unit_periphery',
    'unit_grouping',
    'association_modality',
    'association_marking',
    'association_expression',
    'associated_phenomenon',
    'property_type',
    'relation_type',
    'attribute_type',
    'configuration_type',
    'textual_expression',
    'instantiator_subjectivity',
    'objective_association',
    'process_selection',
    'entity_construal',
    'interactant_indication',
    'entity_definiteness',
    'analysis_type',
    'property_mode',
    'proximity',
    'intensification',
    'association_type',
    'associated_meaning_type',
    'specific_association_type',
    'proximity_type',
    'affected_expression_type',
    'adjustment_type',
    'associated_experience_type',
    'subject_speaker_inclusion',
    'identification_type',
    'modality_assignment',
    'exclusion',
    'group_recursion',
    'normal_progression_type',
    'invoking_of_group',
    'logical_operator_type',
    'operator_expression',
    'exclusion_type',
    'pro-form_person',
    'topicalization',
    'topic_type',
    'sequence_operator_type',
    'collation_strategy',
    'recognition_criterion',
    'embedded_proposition_marking',
    'actualization',
    'diachronic_operation_type',
    'totality',
  ],

  morphologicalSystems: [
    'attentiveness',
    'completion',
    'entity_gender',
    'gendered_type',
    'entity_number',
    'subject_indication',
    'subject_number',
  ],
};

export const allChoices = [
  'configuration',
  'textually_affected_expression',
  'explicitly_interactant',
  'alternation',
  'non-enclitic_operator_root',
  'explicit_direct_address',
  'tbd',
  'explicitly_feminine',
  'associated_relation',
  'peripheral_property',
  'definite_entity',
  'category_of_similar_things',
  'offline_progression',
  'additional_integral_association',
  'associated_experience',
  'name_of_specific_thing',
  'end_act_sequence',
  'synchronic_operation',
  'no_explicit_experiential_construal',
  'explicit_proposition_marker',
  'diachronic_operation',
  'not_necessarily_directive',
  'explicitly_interactant_subject',
  'explicit_experiential_construal',
  'construed_phenomenon',
  'subjective_participant_as_instantiator',
  'not_necessarily_internal_orientation',
  'single_item',
  'elided_as_accessible',
  'not_necessarily_tentative_act',
  'maximal_attentiveness',
  'associated_meaning',
  'continue_act_sequence',
  'explicit_totality',
  'not_necessarily_feminine',
  'collation',
  'single_act',
  'explicitly_complete',
  'process_manifested_by_subjective_participant',
  'yes_no_question',
  'exclusion_of_something_actual_otherwise',
  'explicit_interjection',
  'explicit_instantiator',
  'not_necessarily_expective',
  'explicitly_internal_orientation',
  'replacement_of_earlier_members',
  'minimal_attentiveness',
  'speaker_explicitly_excluded_from_subject',
  'indefinite',
  'explicitly_ostentatious_unit',
  'invoking_of_other_group_members',
  'continue_grouping',
  'not_necessarily_plural_entity',
  'replacement',
  'no_invoking_of_other_group_members',
  'not_necessarily_interactant_subject',
  'not_necessarily_contemplative',
  'not_explicitly_excluded_from_membership',
  'end_turn',
  'temporal_relation',
  'biased_towards_denial',
  'explicitly_directive',
  'explicitly_plural_entity',
  'genitive_association',
  'not_necessarily_plural_subject',
  'dative_association',
  'attribute',
  'speech_act_as_projected_discourse',
  'speech_as_core_of_act',
  'stop_grouping',
  'set_operator_as_discourse_marker',
  'accusative_association',
  'logical_relation',
  'simple_progression',
  'redundant_actualization_marker',
  'progression_towards_completion',
  'explicitly_gendered',
  'explicitly_tentative_act',
  'more_specific_association',
  'independent',
  'no_explicit_instantiator',
  'predication',
  'construed_proposition',
  'associated_entity',
  'explicitly_biased',
  'near',
  'addition',
  'sequence_operator',
  'continue_turn',
  'intrinsic_classification',
  'explicit_proximity',
  'explicitly_expective',
  'prepositional_association_marking',
  'explicitly_contemplative',
  'explicit_intensifier',
  'process_caused_by_subjective_participant',
  'speaker_explicitly_included_in_subject',
  'not_necessarily_interactant',
  'predication_as_abstract_proposition',
  'no_explicit_proximity',
  'sequence_of_acts',
  'speaker_excluded',
  'objective_association_as_instantiator',
  'group_of_items',
  'not_necessarily_actual_otherwise',
  'instantiation_of_event',
  'association',
  'independent_modality',
  'biased_towards_assertion',
  'not_necessarily_gendered',
  'explicitly_plural_subject',
  'inventional_act',
  'extrinsic_depiction',
  'normal_expression',
  'inflectional_association_marking',
  'explicitly_excluded_from_membership',
  'not_necessarily_complete',
  'no_additional_integral_association',
  'explicit_topic',
  'explicit_discourse_progression',
];

export const allSituationalChoices = [
  'no embedded discourse',
  'excluded discourse only',
  'practical-ie-outwardly-oriented',
  'action',
  'projecting',
  'allying',
  'private',
  'monological',
  'non-institutional-or-neutralized',
  'distant',
  'ancillary',
  'addressee-more-passive',
  'spoken',
  'phonic',
  'multilogical',
  'institutional',
  'addressee-more-active',
  'conceptual-ie-internally-oriented',
  'relation',
  'instructing',
  'opposing',
  'neutral',
  'unclear',
  'asserting',
  'close',
  'dialogical',
  'constitutive',
  'disinterested',
  'written',
  'on-someones-side',
  'graphic',
  'contact',
  'equalized',
];

export const situationSystemNetwork = [
  {
    title: 'ABSTRACTNESS-TYPE-(FIELD)',
    key: 'ABSTRACTNESS-TYPE-(FIELD)',
    value: 'ABSTRACTNESS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'conceptual-ie-internally-oriented',
        key: 'conceptual-ie-internally-oriented',
        value: 'conceptual-ie-internally-oriented',
      },
      {
        title: 'practical-ie-outwardly-oriented',
        key: 'practical-ie-outwardly-oriented',
        value: 'practical-ie-outwardly-oriented',
      },
    ],
  },
  {
    title: 'ACTIVITY-FOCUS-(FIELD)',
    key: 'ACTIVITY-FOCUS-(FIELD)',
    value: 'ACTIVITY-FOCUS-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'action',
        key: 'action',
        value: 'action',
      },
      {
        title: 'relation',
        key: 'relation',
        value: 'relation',
      },
      {
        title: 'contact',
        key: 'contact',
        value: 'contact',
      },
    ],
  },
  {
    title: 'GOALS-TYPE-(FIELD)',
    key: 'GOALS-TYPE-(FIELD)',
    value: 'GOALS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'instructing',
        key: 'instructing',
        value: 'instructing',
      },
      {
        title: 'informing',
        key: 'informing',
        value: 'informing',
        children: [
          {
            title: 'INFORMING-TYPE',
            key: 'INFORMING-TYPE',
            value: 'INFORMING-TYPE',
            entryCondition: 'informing',
            children: [
              {
                title: 'projecting',
                key: 'projecting',
                value: 'projecting',
              },
              {
                title: 'asserting',
                key: 'asserting',
                value: 'asserting',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    key: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    value: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'allying',
        key: 'allying',
        value: 'allying',
      },
      {
        title: 'opposing',
        key: 'opposing',
        value: 'opposing',
      },
    ],
  },
  {
    title: 'PUBLICITY-(TENOR)',
    key: 'PUBLICITY-(TENOR)',
    value: 'PUBLICITY-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'onlookers',
        key: 'onlookers',
        value: 'onlookers',
        children: [
          {
            title: 'ONLOOKERS-TYPE',
            key: 'ONLOOKERS-TYPE',
            value: 'ONLOOKERS-TYPE',
            entryCondition: 'onlookers',
            children: [
              {
                title: 'disinterested',
                key: 'disinterested',
                value: 'disinterested',
              },
              {
                title: 'interested',
                key: 'interested',
                value: 'interested',
                children: [
                  {
                    title: 'INTERESTED-TYPE',
                    key: 'INTERESTED-TYPE',
                    value: 'INTERESTED-TYPE',
                    entryCondition: 'interested',
                    children: [
                      {
                        title: 'neutral',
                        key: 'neutral',
                        value: 'neutral',
                      },
                      {
                        title: 'on-someones-side',
                        key: 'on-someones-side',
                        value: 'on-someones-side',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        title: 'private',
        key: 'private',
        value: 'private',
      },
    ],
  },
  {
    title: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    key: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    value: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'monological',
        key: 'monological',
        value: 'monological',
      },
      {
        title: 'more-than-one',
        key: 'more-than-one',
        value: 'more-than-one',
        children: [
          {
            title: 'MORE-THAN-ONE-TYPE',
            key: 'MORE-THAN-ONE-TYPE',
            value: 'MORE-THAN-ONE-TYPE',
            entryCondition: 'more-than-one',
            children: [
              {
                title: 'dialogical',
                key: 'dialogical',
                value: 'dialogical',
              },
              {
                title: 'multilogical',
                key: 'multilogical',
                value: 'multilogical',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'CONTROL-TYPE-(TENOR)',
    key: 'CONTROL-TYPE-(TENOR)',
    value: 'CONTROL-TYPE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'hierarchic',
        key: 'hierarchic',
        value: 'hierarchic',
        children: [
          {
            title: 'HIERARCHIC-TYPE',
            key: 'HIERARCHIC-TYPE',
            value: 'HIERARCHIC-TYPE',
            entryCondition: 'hierarchic',
            children: [
              {
                title: 'institutional',
                key: 'institutional',
                value: 'institutional',
                gloss:
                  'at least one participant represents repercussive power structures',
              },
              {
                title: 'non-institutional-or-neutralized',
                key: 'non-institutional-or-neutralized',
                value: 'non-institutional-or-neutralized',
              },
            ],
          },
        ],
      },
      {
        title: 'non-hierarchic',
        key: 'non-hierarchic',
        value: 'non-hierarchic',
        children: [
          {
            title: 'NON-HIERARCHIC-TYPE',
            key: 'NON-HIERARCHIC-TYPE',
            value: 'NON-HIERARCHIC-TYPE',
            entryCondition: 'non-hierarchic',
            children: [
              {
                title: 'unclear',
                key: 'unclear',
                value: 'unclear',
              },
              {
                title: 'equalized',
                key: 'equalized',
                value: 'equalized',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'SOCIAL-DISTANCE-(TENOR)',
    key: 'SOCIAL-DISTANCE-(TENOR)',
    value: 'SOCIAL-DISTANCE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'close',
        key: 'close',
        value: 'close',
      },
      {
        title: 'distant',
        key: 'distant',
        value: 'distant',
      },
    ],
  },
  {
    title: 'LANGUAGE-ROLE-TYPE-(MODE)',
    key: 'LANGUAGE-ROLE-TYPE-(MODE)',
    value: 'LANGUAGE-ROLE-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'constitutive',
        key: 'constitutive',
        value: 'constitutive',
      },
      {
        title: 'ancillary',
        key: 'ancillary',
        value: 'ancillary',
      },
    ],
  },
  {
    title: 'PROCESS-SHARING-TYPE-(MODE)',
    key: 'PROCESS-SHARING-TYPE-(MODE)',
    value: 'PROCESS-SHARING-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'addressee-more-active',
        key: 'addressee-more-active',
        value: 'addressee-more-active',
      },
      {
        title: 'addressee-more-passive',
        key: 'addressee-more-passive',
        value: 'addressee-more-passive',
      },
    ],
  },
  {
    title: 'CHANNEL-TYPE-(MODE)',
    key: 'CHANNEL-TYPE-(MODE)',
    value: 'CHANNEL-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'phonic',
        key: 'phonic',
        value: 'phonic',
      },
      {
        title: 'graphic',
        key: 'graphic',
        value: 'graphic',
      },
    ],
  },
  {
    title: 'MEDIUM-TYPE-(MODE)',
    key: 'MEDIUM-TYPE-(MODE)',
    value: 'MEDIUM-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'spoken',
        key: 'spoken',
        value: 'spoken',
      },
      {
        title: 'written',
        key: 'written',
        value: 'written',
      },
    ],
  },
];

export const systemsDictionary = {
  field: {
    ABSTRACTNESS: [
      'conceptual-ie-internally-oriented',
      'practical-ie-outwardly-oriented',
    ],
    ACTIVITY_FOCUS: ['action', 'relation', 'contact'],
    GOALS: ['instructing', 'projecting', 'asserting'],
  },
  tenor: {
    VALUE_ORIENTATION_PREDISPOSITION: ['allying', 'opposing'],

    PUBLICITY: ['disinterested', 'neutral', 'on-someones-side', 'private'],
    NUMBER_OF_SPEAKING_PARTICIPANTS: [
      'monological',
      'dialogical',
      'multilogical',
    ],
    CONTROL: [
      'institutional',
      'non-institutional-or-neutralized',
      'unclear',
      'equalized',
    ],
    SOCIAL_DISTANCE: ['close', 'distant'],
  },
  mode: {
    LANGUAGE_ROLE: ['constitutive', 'ancillary'],
    PROCESS_SHARING: ['addressee-more-active', 'addressee-more-passive'],
    CHANNEL: ['phonic', 'graphic'],
    MEDIUM: ['spoken', 'written'],
  },
};

export const allFeaturesSept2021 = [
  '!associated',
  '!attentiveness',
  '!complete',
  '!depicted',
  '!differentiated',
  '!directive',
  '!distributed',
  '!distributedm',
  '!expective',
  '!explicit_subject',
  '!generalized',
  '!inferential',
  '!interactant',
  '!objectified_participant',
  '!process',
  '!reiterated',
  '!secondary_predication',
  '!semiotic',
  '!subject_state',
  '!subordinate',
  '!temporal',
  '!tentative',
  '!topic',
  'actualization',
  'actualization_tbd',
  'affirmative',
  'associated',
  'attentiveness',
  'attentiveness_tbd',
  'basic_thing',
  'co-textual_expression',
  'complete',
  'completeness_tbd',
  'depicted',
  'description_as_depiction',
  'differentiated',
  'direction_tbd',
  'directive',
  'disjunctive',
  'distributed',
  'expectation_tbd',
  'expective',
  'explicit_subject',
  'generalized',
  'inferential',
  'interactant',
  'interactant_subject',
  'logical_set',
  'objectified_participant',
  'plural',
  'process',
  'propositional',
  'reiterated',
  'relativized',
  'secondary_predication',
  'subject_involvement_tbd',
  'subject_number_tbd',
  'subject_state',
  'subordinate',
  'temporal',
  'tentative',
  'topic',
];

export const allSystemsSept2021_probabilities = {
  systems: {
    actualization: {
      actualization: 0.0,
      actualization_tbd: 0.0,
    },
    addition_expression: {
      not_enclitic: 0.0,
      enclitic: 0.0,
    },
    addition_type: {
      not_progressive_addition: 0.0,
      progressive_addition: 0.0,
    },
    address_marking: {
      not_address_marker: 0.0,
      address_marker: 0.0,
    },
    affirmation: {
      not_affirmative: 0.0,
      affirmative: 0.0,
    },
    association: {
      not_associated: 0.0,
      associated: 0.0,
    },
    association_case: {
      accusative_association: 0.0,
      association_case_tbd: 0.0,
      dative_association: 0.0,
      genitive_association: 0.0,
    },
    association_derivation: {
      basic_association: 0.0,
      propositional_association: 0.0,
    },
    attentiveness: {
      not_attentiveness: 0.0,
      attentiveness: 0.0,
      attentiveness_tbd: 0.0,
    },
    base_value: {
      not_invoked_base_value: 0.0,
      base_value_tbd: 0.0,
      invoked_base_value: 0.0,
    },
    bias: {
      not_biased: 0.0,
      biased: 0.0,
    },
    category_selection: 0.0,
    causality: {
      causality_tbd: 0.0,
      doing: 0.0,
      happening: 0.0,
    },
    classification: {
      not_classified: 0.0,
      classified: 0.0,
    },
    'co-textual_expression': { 'co-textual_expression': 0.0 },
    'co-textual_expression_type': { elided_as_accessible: 0.0 },
    completeness: {
      not_complete: 0.0,
      complete: 0.0,
      completeness_tbd: 0.0,
    },
    contemplation: {
      contemplation_tbd: 0.0,
      contemplative: 0.0,
    },
    contrast: { not_contrastive: 0.0 },
    definition: {
      not_generalized: 0.0,
      generalized: 0.0,
    },
    depiction: {
      not_depicted: 0.0,
      depicted: 0.0,
    },
    depiction_derivation: {
      basic_depiction: 0.0,
      description_as_depiction: 0.0,
    },
    depiction_domain: { depiction_domain_tbd: 0.0 },
    description: {
      not_described: 0.0,
      described: 0.0,
    },
    description_derivation: {
      association_as_description: 0.0,
      basic_description: 0.0,
      depiction_as_description: 0.0,
      event_as_description: 0.0,
    },
    description_domain: {
      description_domain_tbd: 0.0,
      measurement: 0.0,
      quantification: 0.0,
    },
    development: {
      not_development: 0.0,
      development: 0.0,
    },
    development_derivation: {
      basic_development: 0.0,
      logical_operation_as_development: 0.0,
      relativization_as_development: 0.0,
    },
    differentiation: {
      not_differentiated: 0.0,
      differentiated: 0.0,
    },
    direct_address: {
      not_direct_address: 0.0,
      direct_address: 0.0,
    },
    direction: {
      not_directive: 0.0,
      direction_tbd: 0.0,
      directive: 0.0,
    },
    distribution: {
      not_distributed: 0.0,
      distributed: 0.0,
    },
    double_negation: { not_double_negation: 0.0 },
    entity_derivation: {
      basic_entity: 0.0,
      objectified_temporal_predication_as_entity: 0.0,
    },
    exclusivity: { exclusive: 0.0 },
    expectation: {
      not_expective: 0.0,
      expectation_tbd: 0.0,
      expective: 0.0,
    },
    gender: {
      not_gendered: 0.0,
      gender_tbd: 0.0,
      gendered: 0.0,
    },
    gendered_type: {
      not_feminine: 0.0,
      feminine: 0.0,
    },
    grouping: {
      not_disjunctive: 0.0,
      disjunctive: 0.0,
    },
    inference_type: {
      likely_inference: 0.0,
      unlikely_inference: 0.0,
    },
    inferential_status: {
      not_inferential: 0.0,
      inferential: 0.0,
    },
    intensity: {
      not_extreme: 0.0,
      extreme: 0.0,
    },
    interjection: {
      not_interjection: 0.0,
      interjection: 0.0,
    },
    interjection_type: { phatic: 0.0 },
    interrelation: {
      not_invocation_of_others: 0.0,
      invocation_of_others: 0.0,
    },
    interrogation: {
      not_elemental: 0.0,
      elemental: 0.0,
    },
    logical_complexity: { logical_set: 0.0 },
    move_making: {
      not_multiple_moves: 0.0,
      multiple_moves: 0.0,
    },
    move_type: {
      not_progressive: 0.0,
      progressive: 0.0,
    },
    name_selection: 0.0,
    naming: {
      not_named: 0.0,
      named: 0.0,
    },
    near_expression: {
      not_idiomatic_article: 0.0,
      idiomatic_article: 0.0,
    },
    negation: {
      not_negative: 0.0,
      negative: 0.0,
    },
    negative_type: {
      not_negated_actual: 0.0,
      negated_actual: 0.0,
    },
    number: {
      not_plural: 0.0,
      number_tbd: 0.0,
      plural: 0.0,
    },
    object_case: {
      not_directional: 0.0,
      directional: 0.0,
      object_case_tbd: 0.0,
    },
    object_direction: {
      from_object: 0.0,
      towards_object: 0.0,
    },
    object_state: { not_object_state: 0.0 },
    objectification: {
      objectified_by_subject: 0.0,
      objectified_by_third_party: 0.0,
    },
    objectification_type: {
      not_suppression_of_lexicalized_subjectivity: 0.0,
      suppression_of_lexicalized_subjectivity: 0.0,
    },
    order_of_experience: {
      not_semiotic: 0.0,
      semiotic: 0.0,
    },
    orientation: {
      internal_orientation: 0.0,
      orientation_tbd: 0.0,
    },
    orientation_shift: { orientation_shift_tbd: 0.0 },
    person: {
      speaker_excluded: 0.0,
      speaker_included: 0.0,
    },
    predication_type: {
      not_temporal: 0.0,
      temporal: 0.0,
    },
    prepositional_marking: {
      not_prepositional: 0.0,
      prepositional: 0.0,
    },
    process_domain: {
      not_process: 0.0,
      process: 0.0,
    },
    process_subdomain: 0.0,
    progressive_move_type: { speech_act: 0.0 },
    proposition_marking: { proposition_marker: 0.0 },
    proximity: {
      far: 0.0,
      near: 0.0,
    },
    quality_delicacy: { quality_delicacy_tbd: 0.0 },
    quotation_marking: {
      not_quotation_marker: 0.0,
      quotation_marker: 0.0,
    },
    're-expression': { multiple_expressions: 0.0 },
    're-expression_marking': {
      'not_re-expression_marker': 0.0,
      're-expression_marker': 0.0,
    },
    reception: {
      not_recipient: 0.0,
      recipient: 0.0,
    },
    reiteration: {
      not_reiterated: 0.0,
      reiterated: 0.0,
    },
    relation_to_others: {
      not_subtractive: 0.0,
      subtractive: 0.0,
    },
    relative_definiteness: {
      not_indefinite_relative: 0.0,
      indefinite_relative: 0.0,
    },
    relativization: {
      not_relativized: 0.0,
      relativized: 0.0,
    },
    secondary_event: {
      not_objectified_event: 0.0,
      objectified_event: 0.0,
    },
    secondary_predication: {
      not_secondary_predication: 0.0,
      secondary_predication: 0.0,
    },
    semiosis_type: {
      expression: 0.0,
      meaning: 0.0,
    },
    similarity: { not_similar: 0.0 },
    situational_progression_type: {
      mainline: 0.0,
      offline: 0.0,
    },
    speaker_shift: { speaker_shift_tbd: 0.0 },
    specification: {
      not_specified: 0.0,
      specified: 0.0,
    },
    speech_act_type: {
      not_propositional: 0.0,
      propositional: 0.0,
    },
    speech_role: {
      not_interactant: 0.0,
      interactant: 0.0,
    },
    subject_construal: {
      not_explicit_subject: 0.0,
      explicit_subject: 0.0,
    },
    subject_involvement: {
      interactant_subject: 0.0,
      subject_involvement_tbd: 0.0,
    },
    subject_number: { subject_number_tbd: 0.0 },
    subject_state: {
      not_subject_state: 0.0,
      subject_state: 0.0,
    },
    subordinate_type: {
      not_integrated_subordinate: 0.0,
      integrated_subordinate: 0.0,
    },
    subordination: {
      not_subordinate: 0.0,
      subordinate: 0.0,
    },
    subtraction_type: {
      exception: 0.0,
      replacement: 0.0,
    },
    tentativeness: {
      not_tentative: 0.0,
      tentative: 0.0,
    },
    thing_derivation: {
      answer_to_question_as_thing: 0.0,
      basic_thing: 0.0,
      event_as_thing: 0.0,
      linguistic_token_as_thing: 0.0,
      participant_in_proposition_as_thing: 0.0,
    },
    topic_type: { not_integrated_topic: 0.0 },
    topicalization: {
      not_topic: 0.0,
      topic: 0.0,
    },
    transitivity: {
      not_objectified_participant: 0.0,
      objectified_participant: 0.0,
    },
  },
};

export const systemLookupByFeatureSept2021 = {
  actualization: 'actualization',
  actualization_tbd: 'actualization',
  not_enclitic: 'addition_expression',
  enclitic: 'addition_expression',
  not_progressive_addition: 'addition_type',
  progressive_addition: 'addition_type',
  not_address_marker: 'address_marking',
  address_marker: 'address_marking',
  not_affirmative: 'affirmation',
  affirmative: 'affirmation',
  not_associated: 'association',
  associated: 'association',
  accusative_association: 'association_case',
  association_case_tbd: 'association_case',
  dative_association: 'association_case',
  genitive_association: 'association_case',
  basic_association: 'association_derivation',
  propositional_association: 'association_derivation',
  not_attentiveness: 'attentiveness',
  attentiveness: 'attentiveness',
  attentiveness_tbd: 'attentiveness',
  not_invoked_base_value: 'base_value',
  base_value_tbd: 'base_value',
  invoked_base_value: 'base_value',
  not_biased: 'bias',
  biased: 'bias',
  causality_tbd: 'causality',
  doing: 'causality',
  happening: 'causality',
  not_classified: 'classification',
  classified: 'classification',
  'co-textual_expression': 'co-textual_expression',
  elided_as_accessible: 'co-textual_expression_type',
  not_complete: 'completeness',
  complete: 'completeness',
  completeness_tbd: 'completeness',
  contemplation_tbd: 'contemplation',
  contemplative: 'contemplation',
  not_contrastive: 'contrast',
  not_generalized: 'definition',
  generalized: 'definition',
  not_depicted: 'depiction',
  depicted: 'depiction',
  basic_depiction: 'depiction_derivation',
  description_as_depiction: 'depiction_derivation',
  depiction_domain_tbd: 'depiction_domain',
  not_described: 'description',
  described: 'description',
  association_as_description: 'description_derivation',
  basic_description: 'description_derivation',
  depiction_as_description: 'description_derivation',
  event_as_description: 'description_derivation',
  description_domain_tbd: 'description_domain',
  measurement: 'description_domain',
  quantification: 'description_domain',
  not_development: 'development',
  development: 'development',
  basic_development: 'development_derivation',
  logical_operation_as_development: 'development_derivation',
  relativization_as_development: 'development_derivation',
  not_differentiated: 'differentiation',
  differentiated: 'differentiation',
  not_direct_address: 'direct_address',
  direct_address: 'direct_address',
  not_directive: 'direction',
  direction_tbd: 'direction',
  directive: 'direction',
  not_distributed: 'distribution',
  distributed: 'distribution',
  not_double_negation: 'double_negation',
  basic_entity: 'entity_derivation',
  objectified_temporal_predication_as_entity: 'entity_derivation',
  exclusive: 'exclusivity',
  not_expective: 'expectation',
  expectation_tbd: 'expectation',
  expective: 'expectation',
  not_gendered: 'gender',
  gender_tbd: 'gender',
  gendered: 'gender',
  not_feminine: 'gendered_type',
  feminine: 'gendered_type',
  not_disjunctive: 'grouping',
  disjunctive: 'grouping',
  likely_inference: 'inference_type',
  unlikely_inference: 'inference_type',
  not_inferential: 'inferential_status',
  inferential: 'inferential_status',
  not_extreme: 'intensity',
  extreme: 'intensity',
  not_interjection: 'interjection',
  interjection: 'interjection',
  phatic: 'interjection_type',
  not_invocation_of_others: 'interrelation',
  invocation_of_others: 'interrelation',
  not_elemental: 'interrogation',
  elemental: 'interrogation',
  logical_set: 'logical_complexity',
  not_multiple_moves: 'move_making',
  multiple_moves: 'move_making',
  not_progressive: 'move_type',
  progressive: 'move_type',
  not_named: 'naming',
  named: 'naming',
  not_idiomatic_article: 'near_expression',
  idiomatic_article: 'near_expression',
  not_negative: 'negation',
  negative: 'negation',
  not_negated_actual: 'negative_type',
  negated_actual: 'negative_type',
  not_plural: 'number',
  number_tbd: 'number',
  plural: 'number',
  not_directional: 'object_case',
  directional: 'object_case',
  object_case_tbd: 'object_case',
  from_object: 'object_direction',
  towards_object: 'object_direction',
  not_object_state: 'object_state',
  objectified_by_subject: 'objectification',
  objectified_by_third_party: 'objectification',
  not_suppression_of_lexicalized_subjectivity: 'objectification_type',
  suppression_of_lexicalized_subjectivity: 'objectification_type',
  not_semiotic: 'order_of_experience',
  semiotic: 'order_of_experience',
  internal_orientation: 'orientation',
  orientation_tbd: 'orientation',
  orientation_shift_tbd: 'orientation_shift',
  speaker_excluded: 'person',
  speaker_included: 'person',
  not_temporal: 'predication_type',
  temporal: 'predication_type',
  not_prepositional: 'prepositional_marking',
  prepositional: 'prepositional_marking',
  not_process: 'process_domain',
  process: 'process_domain',
  speech_act: 'progressive_move_type',
  proposition_marker: 'proposition_marking',
  far: 'proximity',
  near: 'proximity',
  quality_delicacy_tbd: 'quality_delicacy',
  not_quotation_marker: 'quotation_marking',
  quotation_marker: 'quotation_marking',
  multiple_expressions: 'r: -expression',
  'not_re-expression_marker': 're-expression_marking',
  're-expression_marker': 're-expression_marking',
  not_recipient: 'reception',
  recipient: 'reception',
  not_reiterated: 'reiteration',
  reiterated: 'reiteration',
  not_subtractive: 'relation_to_others',
  subtractive: 'relation_to_others',
  not_indefinite_relative: 'relative_definiteness',
  indefinite_relative: 'relative_definiteness',
  not_relativized: 'relativization',
  relativized: 'relativization',
  not_objectified_event: 'secondary_event',
  objectified_event: 'secondary_event',
  not_secondary_predication: 'secondary_predication',
  secondary_predication: 'secondary_predication',
  expression: 'semiosis_type',
  meaning: 'semiosis_type',
  not_similar: 'similarity',
  mainline: 'situational_progression_type',
  offline: 'situational_progression_type',
  speaker_shift_tbd: 'speaker_shift',
  not_specified: 'specification',
  specified: 'specification',
  not_propositional: 'speech_act_type',
  propositional: 'speech_act_type',
  not_interactant: 'speech_role',
  interactant: 'speech_role',
  not_explicit_subject: 'subject_construal',
  explicit_subject: 'subject_construal',
  interactant_subject: 'subject_involvement',
  subject_involvement_tbd: 'subject_involvement',
  subject_number_tbd: 'subject_number',
  not_subject_state: 'subject_state',
  subject_state: 'subject_state',
  not_integrated_subordinate: 'subordinate_type',
  integrated_subordinate: 'subordinate_type',
  not_subordinate: 'subordination',
  subordinate: 'subordination',
  exception: 'subtraction_type',
  replacement: 'subtraction_type',
  not_tentative: 'tentativeness',
  tentative: 'tentativeness',
  answer_to_question_as_thing: 'thing_derivation',
  basic_thing: 'thing_derivation',
  event_as_thing: 'thing_derivation',
  linguistic_token_as_thing: 'thing_derivation',
  participant_in_proposition_as_thing: 'thing_derivation',
  not_integrated_topic: 'topic_type',
  not_topic: 'topicalization',
  topic: 'topicalization',
  not_objectified_participant: 'transitivity',
  objectified_participant: 'transitivity',
};
