export const systemGroups = {
  moveSystems: ['move_recursion'],

  actSystems: [
    'act_tentativeness',
    'act_recursion',
    'act_progression',
    'act_type',
    'act_sequencing',
    'direction',
    'contemplation',
    'conventionality',
    'orientation',
    'interjection',
    'expectation',
    'question_type',
    'yes_no_type',
    'bias_type',
  ],

  discourseSystems: [
    'discourse_marker_type',
    'ostentation',
    'direct_address',
    'proposition_marking',
    'operator_as_marker_type',
  ],

  otherSystems: [
    'combination_type',
    'speech_centrality',
    'instantiator_expression',
    'unit_periphery',
    'unit_grouping',
    'association_modality',
    'association_marking',
    'association_expression',
    'associated_phenomenon',
    'property_type',
    'relation_type',
    'attribute_type',
    'configuration_type',
    'textual_expression',
    'instantiator_subjectivity',
    'objective_association',
    'process_selection',
    'entity_construal',
    'interactant_indication',
    'entity_definiteness',
    'analysis_type',
    'property_mode',
    'proximity',
    'intensification',
    'association_type',
    'associated_meaning_type',
    'specific_association_type',
    'proximity_type',
    'affected_expression_type',
    'adjustment_type',
    'associated_experience_type',
    'subject_speaker_inclusion',
    'identification_type',
    'modality_assignment',
    'exclusion',
    'group_recursion',
    'normal_progression_type',
    'invoking_of_group',
    'logical_operator_type',
    'operator_expression',
    'exclusion_type',
    'pro-form_person',
    'topicalization',
    'topic_type',
    'sequence_operator_type',
    'collation_strategy',
    'recognition_criterion',
    'embedded_proposition_marking',
    'actualization',
    'diachronic_operation_type',
    'totality',
  ],

  morphologicalSystems: [
    'attentiveness',
    'completion',
    'entity_gender',
    'gendered_type',
    'entity_number',
    'subject_indication',
    'subject_number',
  ],
};

export const allChoices = [
  'configuration',
  'textually_affected_expression',
  'explicitly_interactant',
  'alternation',
  'non-enclitic_operator_root',
  'explicit_direct_address',
  'tbd',
  'explicitly_feminine',
  'associated_relation',
  'peripheral_property',
  'definite_entity',
  'category_of_similar_things',
  'offline_progression',
  'additional_integral_association',
  'associated_experience',
  'name_of_specific_thing',
  'end_act_sequence',
  'synchronic_operation',
  'no_explicit_experiential_construal',
  'explicit_proposition_marker',
  'diachronic_operation',
  'not_necessarily_directive',
  'explicitly_interactant_subject',
  'explicit_experiential_construal',
  'construed_phenomenon',
  'subjective_participant_as_instantiator',
  'not_necessarily_internal_orientation',
  'single_item',
  'elided_as_accessible',
  'not_necessarily_tentative_act',
  'maximal_attentiveness',
  'associated_meaning',
  'continue_act_sequence',
  'explicit_totality',
  'not_necessarily_feminine',
  'collation',
  'single_act',
  'explicitly_complete',
  'process_manifested_by_subjective_participant',
  'yes_no_question',
  'exclusion_of_something_actual_otherwise',
  'explicit_interjection',
  'explicit_instantiator',
  'not_necessarily_expective',
  'explicitly_internal_orientation',
  'replacement_of_earlier_members',
  'minimal_attentiveness',
  'speaker_explicitly_excluded_from_subject',
  'indefinite',
  'explicitly_ostentatious_unit',
  'invoking_of_other_group_members',
  'continue_grouping',
  'not_necessarily_plural_entity',
  'replacement',
  'no_invoking_of_other_group_members',
  'not_necessarily_interactant_subject',
  'not_necessarily_contemplative',
  'not_explicitly_excluded_from_membership',
  'end_turn',
  'temporal_relation',
  'biased_towards_denial',
  'explicitly_directive',
  'explicitly_plural_entity',
  'genitive_association',
  'not_necessarily_plural_subject',
  'dative_association',
  'attribute',
  'speech_act_as_projected_discourse',
  'speech_as_core_of_act',
  'stop_grouping',
  'set_operator_as_discourse_marker',
  'accusative_association',
  'logical_relation',
  'simple_progression',
  'redundant_actualization_marker',
  'progression_towards_completion',
  'explicitly_gendered',
  'explicitly_tentative_act',
  'more_specific_association',
  'independent',
  'no_explicit_instantiator',
  'predication',
  'construed_proposition',
  'associated_entity',
  'explicitly_biased',
  'near',
  'addition',
  'sequence_operator',
  'continue_turn',
  'intrinsic_classification',
  'explicit_proximity',
  'explicitly_expective',
  'prepositional_association_marking',
  'explicitly_contemplative',
  'explicit_intensifier',
  'process_caused_by_subjective_participant',
  'speaker_explicitly_included_in_subject',
  'not_necessarily_interactant',
  'predication_as_abstract_proposition',
  'no_explicit_proximity',
  'sequence_of_acts',
  'speaker_excluded',
  'objective_association_as_instantiator',
  'group_of_items',
  'not_necessarily_actual_otherwise',
  'instantiation_of_event',
  'association',
  'independent_modality',
  'biased_towards_assertion',
  'not_necessarily_gendered',
  'explicitly_plural_subject',
  'inventional_act',
  'extrinsic_depiction',
  'normal_expression',
  'inflectional_association_marking',
  'explicitly_excluded_from_membership',
  'not_necessarily_complete',
  'no_additional_integral_association',
  'explicit_topic',
  'explicit_discourse_progression',
];

export const allSituationalChoices = [
  'no embedded discourse',
  'excluded discourse only',
  'practical-ie-outwardly-oriented',
  'experiential',
  'projecting',
  'allying',
  'private',
  'monological',
  'non-institutional-or-neutralized',
  'distant',
  'ancillary',
  'addressee-more-passive',
  'spoken',
  'phonic',
  'multilogical',
  'institutional',
  'addressee-more-active',
  'conceptual-ie-internally-oriented',
  'interpersonal',
  'instructing',
  'opposing',
  'neutral',
  'unclear',
  'asserting',
  'close',
  'dialogical',
  'constitutive',
  'disinterested',
  'written',
  'on-someones-side',
  'graphic',
  'logical',
  'equalized',
];

export const situationSystemNetwork = [
  {
    title: 'ABSTRACTNESS-TYPE-(FIELD)',
    key: 'ABSTRACTNESS-TYPE-(FIELD)',
    value: 'ABSTRACTNESS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'conceptual-ie-internally-oriented',
        key: 'conceptual-ie-internally-oriented',
        value: 'conceptual-ie-internally-oriented',
      },
      {
        title: 'practical-ie-outwardly-oriented',
        key: 'practical-ie-outwardly-oriented',
        value: 'practical-ie-outwardly-oriented',
      },
    ],
  },
  {
    title: 'ACTIVITY-FOCUS-(FIELD)',
    key: 'ACTIVITY-FOCUS-(FIELD)',
    value: 'ACTIVITY-FOCUS-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'experiential',
        key: 'experiential',
        value: 'experiential',
      },
      {
        title: 'interpersonal',
        key: 'interpersonal',
        value: 'interpersonal',
      },
      {
        title: 'logical',
        key: 'logical',
        value: 'logical',
      },
    ],
  },
  {
    title: 'GOALS-TYPE-(FIELD)',
    key: 'GOALS-TYPE-(FIELD)',
    value: 'GOALS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'instructing',
        key: 'instructing',
        value: 'instructing',
      },
      {
        title: 'informing',
        key: 'informing',
        value: 'informing',
        children: [
          {
            title: 'INFORMING-TYPE',
            key: 'INFORMING-TYPE',
            value: 'INFORMING-TYPE',
            entryCondition: 'informing',
            children: [
              {
                title: 'projecting',
                key: 'projecting',
                value: 'projecting',
              },
              {
                title: 'asserting',
                key: 'asserting',
                value: 'asserting',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    key: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    value: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'allying',
        key: 'allying',
        value: 'allying',
      },
      {
        title: 'opposing',
        key: 'opposing',
        value: 'opposing',
      },
    ],
  },
  {
    title: 'PUBLICITY-(TENOR)',
    key: 'PUBLICITY-(TENOR)',
    value: 'PUBLICITY-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'onlookers',
        key: 'onlookers',
        value: 'onlookers',
        children: [
          {
            title: 'ONLOOKERS-TYPE',
            key: 'ONLOOKERS-TYPE',
            value: 'ONLOOKERS-TYPE',
            entryCondition: 'onlookers',
            children: [
              {
                title: 'disinterested',
                key: 'disinterested',
                value: 'disinterested',
              },
              {
                title: 'interested',
                key: 'interested',
                value: 'interested',
                children: [
                  {
                    title: 'INTERESTED-TYPE',
                    key: 'INTERESTED-TYPE',
                    value: 'INTERESTED-TYPE',
                    entryCondition: 'interested',
                    children: [
                      {
                        title: 'neutral',
                        key: 'neutral',
                        value: 'neutral',
                      },
                      {
                        title: 'on-someones-side',
                        key: 'on-someones-side',
                        value: 'on-someones-side',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        title: 'private',
        key: 'private',
        value: 'private',
      },
    ],
  },
  {
    title: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    key: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    value: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'monological',
        key: 'monological',
        value: 'monological',
      },
      {
        title: 'more-than-one',
        key: 'more-than-one',
        value: 'more-than-one',
        children: [
          {
            title: 'MORE-THAN-ONE-TYPE',
            key: 'MORE-THAN-ONE-TYPE',
            value: 'MORE-THAN-ONE-TYPE',
            entryCondition: 'more-than-one',
            children: [
              {
                title: 'dialogical',
                key: 'dialogical',
                value: 'dialogical',
              },
              {
                title: 'multilogical',
                key: 'multilogical',
                value: 'multilogical',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'CONTROL-TYPE-(TENOR)',
    key: 'CONTROL-TYPE-(TENOR)',
    value: 'CONTROL-TYPE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'hierarchic',
        key: 'hierarchic',
        value: 'hierarchic',
        children: [
          {
            title: 'HIERARCHIC-TYPE',
            key: 'HIERARCHIC-TYPE',
            value: 'HIERARCHIC-TYPE',
            entryCondition: 'hierarchic',
            children: [
              {
                title: 'institutional',
                key: 'institutional',
                value: 'institutional',
                gloss:
                  'at least one participant represents repercussive power structures',
              },
              {
                title: 'non-institutional-or-neutralized',
                key: 'non-institutional-or-neutralized',
                value: 'non-institutional-or-neutralized',
              },
            ],
          },
        ],
      },
      {
        title: 'non-hierarchic',
        key: 'non-hierarchic',
        value: 'non-hierarchic',
        children: [
          {
            title: 'NON-HIERARCHIC-TYPE',
            key: 'NON-HIERARCHIC-TYPE',
            value: 'NON-HIERARCHIC-TYPE',
            entryCondition: 'non-hierarchic',
            children: [
              {
                title: 'unclear',
                key: 'unclear',
                value: 'unclear',
              },
              {
                title: 'equalized',
                key: 'equalized',
                value: 'equalized',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'SOCIAL-DISTANCE-(TENOR)',
    key: 'SOCIAL-DISTANCE-(TENOR)',
    value: 'SOCIAL-DISTANCE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'close',
        key: 'close',
        value: 'close',
      },
      {
        title: 'distant',
        key: 'distant',
        value: 'distant',
      },
    ],
  },
  {
    title: 'LANGUAGE-ROLE-TYPE-(MODE)',
    key: 'LANGUAGE-ROLE-TYPE-(MODE)',
    value: 'LANGUAGE-ROLE-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'constitutive',
        key: 'constitutive',
        value: 'constitutive',
      },
      {
        title: 'ancillary',
        key: 'ancillary',
        value: 'ancillary',
      },
    ],
  },
  {
    title: 'PROCESS-SHARING-TYPE-(MODE)',
    key: 'PROCESS-SHARING-TYPE-(MODE)',
    value: 'PROCESS-SHARING-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'addressee-more-active',
        key: 'addressee-more-active',
        value: 'addressee-more-active',
      },
      {
        title: 'addressee-more-passive',
        key: 'addressee-more-passive',
        value: 'addressee-more-passive',
      },
    ],
  },
  {
    title: 'CHANNEL-TYPE-(MODE)',
    key: 'CHANNEL-TYPE-(MODE)',
    value: 'CHANNEL-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'phonic',
        key: 'phonic',
        value: 'phonic',
      },
      {
        title: 'graphic',
        key: 'graphic',
        value: 'graphic',
      },
    ],
  },
  {
    title: 'MEDIUM-TYPE-(MODE)',
    key: 'MEDIUM-TYPE-(MODE)',
    value: 'MEDIUM-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'spoken',
        key: 'spoken',
        value: 'spoken',
      },
      {
        title: 'written',
        key: 'written',
        value: 'written',
      },
    ],
  },
];

export const systemsDictionary = {
  field: {
    ABSTRACTNESS: [
      'conceptual-ie-internally-oriented',
      'practical-ie-outwardly-oriented',
    ],
    ACTIVITY_FOCUS: ['experiential', 'interpersonal', 'logical'],
    GOALS: ['instructing', 'projecting', 'asserting'],
  },
  tenor: {
    VALUE_ORIENTATION_PREDISPOSITION: ['allying', 'opposing'],

    PUBLICITY: ['disinterested', 'neutral', 'on-someones-side', 'private'],
    NUMBER_OF_SPEAKING_PARTICIPANTS: [
      'monological',
      'dialogical',
      'multilogical',
    ],
    CONTROL: [
      'institutional',
      'non-institutional-or-neutralized',
      'unclear',
      'equalized',
    ],
    SOCIAL_DISTANCE: ['close', 'distant'],
  },
  mode: {
    LANGUAGE_ROLE: ['constitutive', 'ancillary'],
    PROCESS_SHARING: ['addressee-more-active', 'addressee-more-passive'],
    CHANNEL: ['phonic', 'graphic'],
    MEDIUM: ['spoken', 'written'],
  },
};

export const allFeaturesSept2021 = [
  'not_associated',
  'not_attentiveness',
  'not_complete',
  'not_depicted',
  'not_differentiated',
  'not_directive',
  'not_distributed',
  'not_distributedm',
  'not_expective',
  'not_explicit_subject',
  'not_generalized',
  'not_inferential',
  'not_interactant',
  'not_objectified_participant',
  'not_process',
  'not_reiterated',
  'not_secondary_predication',
  'not_semiotic',
  'not_subject_state',
  'not_subordinate',
  'not_temporal',
  'not_tentative',
  'not_topic',
  'actualization',
  'actualization_tbd',
  'affirmative',
  'associated',
  'attentiveness',
  'attentiveness_tbd',
  'basic_thing',
  'co-textual_expression',
  'complete',
  'completeness_tbd',
  'depicted',
  'description_as_depiction',
  'differentiated',
  'direction_tbd',
  'directive',
  'disjunctive',
  'distributed',
  'expectation_tbd',
  'expective',
  'explicit_subject',
  'generalized',
  'inferential',
  'interactant',
  'interactant_subject',
  'logical_set',
  'objectified_participant',
  'plural',
  'process',
  'propositional',
  'reiterated',
  'relativized',
  'secondary_predication',
  'subject_involvement_tbd',
  'subject_number_tbd',
  'subject_state',
  'subordinate',
  'temporal',
  'tentative',
  'topic',
];

export const allSystemsSept2021_probabilities = {
  systems: {
    actualization: {
      actualization: 0.0,
      actualization_tbd: 0.0,
    },
    addition_expression: {
      not_enclitic: 0.0,
      enclitic: 0.0,
    },
    addition_type: {
      not_progressive_addition: 0.0,
      progressive_addition: 0.0,
    },
    address_marking: {
      not_address_marker: 0.0,
      address_marker: 0.0,
    },
    affirmation: {
      not_affirmative: 0.0,
      affirmative: 0.0,
    },
    association: {
      not_associated: 0.0,
      associated: 0.0,
    },
    association_case: {
      accusative_association: 0.0,
      association_case_tbd: 0.0,
      dative_association: 0.0,
      genitive_association: 0.0,
    },
    association_derivation: {
      basic_association: 0.0,
      propositional_association: 0.0,
    },
    attentiveness: {
      not_attentiveness: 0.0,
      attentiveness: 0.0,
      attentiveness_tbd: 0.0,
    },
    base_value: {
      not_invoked_base_value: 0.0,
      base_value_tbd: 0.0,
      invoked_base_value: 0.0,
    },
    bias: {
      not_biased: 0.0,
      biased: 0.0,
    },
    category_selection: 0.0,
    causality: {
      causality_tbd: 0.0,
      doing: 0.0,
      happening: 0.0,
    },
    classification: {
      not_classified: 0.0,
      classified: 0.0,
    },
    'co-textual_expression': { 'co-textual_expression': 0.0 },
    'co-textual_expression_type': { elided_as_accessible: 0.0 },
    completeness: {
      not_complete: 0.0,
      complete: 0.0,
      completeness_tbd: 0.0,
    },
    contemplation: {
      contemplation_tbd: 0.0,
      contemplative: 0.0,
    },
    contrast: { not_contrastive: 0.0 },
    definition: {
      not_generalized: 0.0,
      generalized: 0.0,
    },
    depiction: {
      not_depicted: 0.0,
      depicted: 0.0,
    },
    depiction_derivation: {
      basic_depiction: 0.0,
      description_as_depiction: 0.0,
    },
    depiction_domain: { depiction_domain_tbd: 0.0 },
    description: {
      not_described: 0.0,
      described: 0.0,
    },
    description_derivation: {
      association_as_description: 0.0,
      basic_description: 0.0,
      depiction_as_description: 0.0,
      event_as_description: 0.0,
    },
    description_domain: {
      description_domain_tbd: 0.0,
      measurement: 0.0,
      quantification: 0.0,
    },
    development: {
      not_development: 0.0,
      development: 0.0,
    },
    development_derivation: {
      basic_development: 0.0,
      logical_operation_as_development: 0.0,
      relativization_as_development: 0.0,
    },
    differentiation: {
      not_differentiated: 0.0,
      differentiated: 0.0,
    },
    direct_address: {
      not_direct_address: 0.0,
      direct_address: 0.0,
    },
    direction: {
      not_directive: 0.0,
      direction_tbd: 0.0,
      directive: 0.0,
    },
    distribution: {
      not_distributed: 0.0,
      distributed: 0.0,
    },
    double_negation: { not_double_negation: 0.0 },
    entity_derivation: {
      basic_entity: 0.0,
      objectified_temporal_predication_as_entity: 0.0,
    },
    exclusivity: { exclusive: 0.0 },
    expectation: {
      not_expective: 0.0,
      expectation_tbd: 0.0,
      expective: 0.0,
    },
    gender: {
      not_gendered: 0.0,
      gender_tbd: 0.0,
      gendered: 0.0,
    },
    gendered_type: {
      not_feminine: 0.0,
      feminine: 0.0,
    },
    grouping: {
      not_disjunctive: 0.0,
      disjunctive: 0.0,
    },
    inference_type: {
      likely_inference: 0.0,
      unlikely_inference: 0.0,
    },
    inferential_status: {
      not_inferential: 0.0,
      inferential: 0.0,
    },
    intensity: {
      not_extreme: 0.0,
      extreme: 0.0,
    },
    interjection: {
      not_interjection: 0.0,
      interjection: 0.0,
    },
    interjection_type: { phatic: 0.0 },
    interrelation: {
      not_invocation_of_others: 0.0,
      invocation_of_others: 0.0,
    },
    interrogation: {
      not_elemental: 0.0,
      elemental: 0.0,
    },
    logical_complexity: { logical_set: 0.0 },
    move_making: {
      not_multiple_moves: 0.0,
      multiple_moves: 0.0,
    },
    move_type: {
      not_progressive: 0.0,
      progressive: 0.0,
    },
    name_selection: 0.0,
    naming: {
      not_named: 0.0,
      named: 0.0,
    },
    near_expression: {
      not_idiomatic_article: 0.0,
      idiomatic_article: 0.0,
    },
    negation: {
      not_negative: 0.0,
      negative: 0.0,
    },
    negative_type: {
      not_negated_actual: 0.0,
      negated_actual: 0.0,
    },
    number: {
      not_plural: 0.0,
      number_tbd: 0.0,
      plural: 0.0,
    },
    object_case: {
      not_directional: 0.0,
      directional: 0.0,
      object_case_tbd: 0.0,
    },
    object_direction: {
      from_object: 0.0,
      towards_object: 0.0,
    },
    object_state: { not_object_state: 0.0 },
    objectification: {
      objectified_by_subject: 0.0,
      objectified_by_third_party: 0.0,
    },
    objectification_type: {
      not_suppression_of_lexicalized_subjectivity: 0.0,
      suppression_of_lexicalized_subjectivity: 0.0,
    },
    order_of_experience: {
      not_semiotic: 0.0,
      semiotic: 0.0,
    },
    orientation: {
      internal_orientation: 0.0,
      orientation_tbd: 0.0,
    },
    orientation_shift: { orientation_shift_tbd: 0.0 },
    person: {
      speaker_excluded: 0.0,
      speaker_included: 0.0,
    },
    predication_type: {
      not_temporal: 0.0,
      temporal: 0.0,
    },
    prepositional_marking: {
      not_prepositional: 0.0,
      prepositional: 0.0,
    },
    process_domain: {
      not_process: 0.0,
      process: 0.0,
    },
    process_subdomain: 0.0,
    progressive_move_type: { speech_act: 0.0 },
    proposition_marking: { proposition_marker: 0.0 },
    proximity: {
      far: 0.0,
      near: 0.0,
    },
    quality_delicacy: { quality_delicacy_tbd: 0.0 },
    quotation_marking: {
      not_quotation_marker: 0.0,
      quotation_marker: 0.0,
    },
    re_expression: { multiple_expressions: 0.0 },
    re_expression_marking: {
      not_re_expression_marker: 0.0,
      re_expression_marker: 0.0,
    },
    reception: {
      not_recipient: 0.0,
      recipient: 0.0,
    },
    reiteration: {
      not_reiterated: 0.0,
      reiterated: 0.0,
    },
    relation_to_others: {
      not_subtractive: 0.0,
      subtractive: 0.0,
    },
    relative_definiteness: {
      not_indefinite_relative: 0.0,
      indefinite_relative: 0.0,
    },
    relativization: {
      not_relativized: 0.0,
      relativized: 0.0,
    },
    secondary_event: {
      not_objectified_event: 0.0,
      objectified_event: 0.0,
    },
    secondary_predication: {
      not_secondary_predication: 0.0,
      secondary_predication: 0.0,
    },
    semiosis_type: {
      expression: 0.0,
      meaning: 0.0,
    },
    similarity: { not_similar: 0.0 },
    situational_progression_type: {
      mainline: 0.0,
      offline: 0.0,
    },
    speaker_shift: { speaker_shift_tbd: 0.0 },
    specification: {
      not_specified: 0.0,
      specified: 0.0,
    },
    speech_act_type: {
      not_propositional: 0.0,
      propositional: 0.0,
    },
    speech_role: {
      not_interactant: 0.0,
      interactant: 0.0,
    },
    subject_construal: {
      not_explicit_subject: 0.0,
      explicit_subject: 0.0,
    },
    subject_involvement: {
      interactant_subject: 0.0,
      subject_involvement_tbd: 0.0,
    },
    subject_number: { subject_number_tbd: 0.0 },
    subject_state: {
      not_subject_state: 0.0,
      subject_state: 0.0,
    },
    subordinate_type: {
      not_integrated_subordinate: 0.0,
      integrated_subordinate: 0.0,
    },
    subordination: {
      not_subordinate: 0.0,
      subordinate: 0.0,
    },
    subtraction_type: {
      exception: 0.0,
      replacement: 0.0,
    },
    tentativeness: {
      not_tentative: 0.0,
      tentative: 0.0,
    },
    thing_derivation: {
      answer_to_question_as_thing: 0.0,
      basic_thing: 0.0,
      event_as_thing: 0.0,
      linguistic_token_as_thing: 0.0,
      participant_in_proposition_as_thing: 0.0,
    },
    topic_type: { not_integrated_topic: 0.0 },
    topicalization: {
      not_topic: 0.0,
      topic: 0.0,
    },
    transitivity: {
      not_objectified_participant: 0.0,
      objectified_participant: 0.0,
    },
  },
};

export const systemLookupByFeatureSept2021 = {
  actualization: 'actualization',
  actualization_tbd: 'actualization',
  not_enclitic: 'addition_expression',
  enclitic: 'addition_expression',
  not_progressive_addition: 'addition_type',
  progressive_addition: 'addition_type',
  not_address_marker: 'address_marking',
  address_marker: 'address_marking',
  not_affirmative: 'affirmation',
  affirmative: 'affirmation',
  not_associated: 'association',
  associated: 'association',
  accusative_association: 'association_case',
  association_case_tbd: 'association_case',
  dative_association: 'association_case',
  genitive_association: 'association_case',
  basic_association: 'association_derivation',
  propositional_association: 'association_derivation',
  not_attentiveness: 'attentiveness',
  attentiveness: 'attentiveness',
  attentiveness_tbd: 'attentiveness',
  not_invoked_base_value: 'base_value',
  base_value_tbd: 'base_value',
  invoked_base_value: 'base_value',
  not_biased: 'bias',
  biased: 'bias',
  causality_tbd: 'causality',
  doing: 'causality',
  happening: 'causality',
  not_classified: 'classification',
  classified: 'classification',
  'co-textual_expression': 'co-textual_expression',
  elided_as_accessible: 'co-textual_expression_type',
  not_complete: 'completeness',
  complete: 'completeness',
  completeness_tbd: 'completeness',
  contemplation_tbd: 'contemplation',
  contemplative: 'contemplation',
  not_contrastive: 'contrast',
  not_generalized: 'definition',
  generalized: 'definition',
  not_depicted: 'depiction',
  depicted: 'depiction',
  basic_depiction: 'depiction_derivation',
  description_as_depiction: 'depiction_derivation',
  depiction_domain_tbd: 'depiction_domain',
  not_described: 'description',
  described: 'description',
  association_as_description: 'description_derivation',
  basic_description: 'description_derivation',
  depiction_as_description: 'description_derivation',
  event_as_description: 'description_derivation',
  description_domain_tbd: 'description_domain',
  measurement: 'description_domain',
  quantification: 'description_domain',
  not_development: 'development',
  development: 'development',
  basic_development: 'development_derivation',
  logical_operation_as_development: 'development_derivation',
  relativization_as_development: 'development_derivation',
  not_differentiated: 'differentiation',
  differentiated: 'differentiation',
  not_direct_address: 'direct_address',
  direct_address: 'direct_address',
  not_directive: 'direction',
  direction_tbd: 'direction',
  directive: 'direction',
  not_distributed: 'distribution',
  distributed: 'distribution',
  not_double_negation: 'double_negation',
  basic_entity: 'entity_derivation',
  objectified_temporal_predication_as_entity: 'entity_derivation',
  exclusive: 'exclusivity',
  not_expective: 'expectation',
  expectation_tbd: 'expectation',
  expective: 'expectation',
  not_gendered: 'gender',
  gender_tbd: 'gender',
  gendered: 'gender',
  not_feminine: 'gendered_type',
  feminine: 'gendered_type',
  not_disjunctive: 'grouping',
  disjunctive: 'grouping',
  likely_inference: 'inference_type',
  unlikely_inference: 'inference_type',
  not_inferential: 'inferential_status',
  inferential: 'inferential_status',
  not_extreme: 'intensity',
  extreme: 'intensity',
  not_interjection: 'interjection',
  interjection: 'interjection',
  phatic: 'interjection_type',
  not_invocation_of_others: 'interrelation',
  invocation_of_others: 'interrelation',
  not_elemental: 'interrogation',
  elemental: 'interrogation',
  logical_set: 'logical_complexity',
  not_multiple_moves: 'move_making',
  multiple_moves: 'move_making',
  not_progressive: 'move_type',
  progressive: 'move_type',
  not_named: 'naming',
  named: 'naming',
  not_idiomatic_article: 'near_expression',
  idiomatic_article: 'near_expression',
  not_negative: 'negation',
  negative: 'negation',
  not_negated_actual: 'negative_type',
  negated_actual: 'negative_type',
  not_plural: 'number',
  number_tbd: 'number',
  plural: 'number',
  not_directional: 'object_case',
  directional: 'object_case',
  object_case_tbd: 'object_case',
  from_object: 'object_direction',
  towards_object: 'object_direction',
  not_object_state: 'object_state',
  objectified_by_subject: 'objectification',
  objectified_by_third_party: 'objectification',
  not_suppression_of_lexicalized_subjectivity: 'objectification_type',
  suppression_of_lexicalized_subjectivity: 'objectification_type',
  not_semiotic: 'order_of_experience',
  semiotic: 'order_of_experience',
  internal_orientation: 'orientation',
  orientation_tbd: 'orientation',
  orientation_shift_tbd: 'orientation_shift',
  speaker_excluded: 'person',
  speaker_included: 'person',
  not_temporal: 'predication_type',
  temporal: 'predication_type',
  not_prepositional: 'prepositional_marking',
  prepositional: 'prepositional_marking',
  not_process: 'process_domain',
  process: 'process_domain',
  speech_act: 'progressive_move_type',
  proposition_marker: 'proposition_marking',
  far: 'proximity',
  near: 'proximity',
  quality_delicacy_tbd: 'quality_delicacy',
  not_quotation_marker: 'quotation_marking',
  quotation_marker: 'quotation_marking',
  multiple_expressions: 'r: -expression',
  not_re_expression_marker: 're_expression_marking',
  re_expression_marker: 're_expression_marking',
  not_recipient: 'reception',
  recipient: 'reception',
  not_reiterated: 'reiteration',
  reiterated: 'reiteration',
  not_subtractive: 'relation_to_others',
  subtractive: 'relation_to_others',
  not_indefinite_relative: 'relative_definiteness',
  indefinite_relative: 'relative_definiteness',
  not_relativized: 'relativization',
  relativized: 'relativization',
  not_objectified_event: 'secondary_event',
  objectified_event: 'secondary_event',
  not_secondary_predication: 'secondary_predication',
  secondary_predication: 'secondary_predication',
  expression: 'semiosis_type',
  meaning: 'semiosis_type',
  not_similar: 'similarity',
  mainline: 'situational_progression_type',
  offline: 'situational_progression_type',
  speaker_shift_tbd: 'speaker_shift',
  not_specified: 'specification',
  specified: 'specification',
  not_propositional: 'speech_act_type',
  propositional: 'speech_act_type',
  not_interactant: 'speech_role',
  interactant: 'speech_role',
  not_explicit_subject: 'subject_construal',
  explicit_subject: 'subject_construal',
  interactant_subject: 'subject_involvement',
  subject_involvement_tbd: 'subject_involvement',
  subject_number_tbd: 'subject_number',
  not_subject_state: 'subject_state',
  subject_state: 'subject_state',
  not_integrated_subordinate: 'subordinate_type',
  integrated_subordinate: 'subordinate_type',
  not_subordinate: 'subordination',
  subordinate: 'subordination',
  exception: 'subtraction_type',
  replacement: 'subtraction_type',
  not_tentative: 'tentativeness',
  tentative: 'tentativeness',
  answer_to_question_as_thing: 'thing_derivation',
  basic_thing: 'thing_derivation',
  event_as_thing: 'thing_derivation',
  linguistic_token_as_thing: 'thing_derivation',
  participant_in_proposition_as_thing: 'thing_derivation',
  not_integrated_topic: 'topic_type',
  not_topic: 'topicalization',
  topic: 'topicalization',
  not_objectified_participant: 'transitivity',
  objectified_participant: 'transitivity',
};

export const excludedFeatures = [
  '(I)',
  '(II)',
  'XSL_error',
  'GBI_error',
  'speak',
];

export const morphologicalFeatures = 'indicative participle infinitive subjunctive imperative optative singular plural third second first aorist present imperfect future perfect pluperfect active passive middle middlepassive feminine masculine neuter nominative genitive accusative dative vocative active passive middle middlepassive noun verb det conj pron prep adj adv ptcl num intj'.split(
  ' ',
);

export const morphSystemLookupByFeature = {
  active: 'voice',
  passive: 'voice',
  middle: 'voice',
  middlepassive: 'voice',
  feminine: 'gender',
  masculine: 'gender',
  neuter: 'gender',
  nominative: 'case',
  genitive: 'case',
  accusative: 'case',
  dative: 'case',
  vocative: 'case',
  active: 'voice',
  passive: 'voice',
  middle: 'voice',
  middlepassive: 'voice',
  noun: 'pos',
  verb: 'pos',
  det: 'pos',
  conj: 'pos',
  pron: 'pos',
  prep: 'pos',
  adj: 'pos',
  adv: 'pos',
  ptcl: 'pos',
  num: 'pos',
  intj: 'pos',
  indicative: 'mood',
  participle: 'mood',
  infinitive: 'mood',
  subjunctive: 'mood',
  imperative: 'mood',
  optative: 'mood',
  singular: 'number',
  plural: 'number',
  third: 'person',
  second: 'person',
  first: 'person',
  aorist: 'tense',
  present: 'tense',
  imperfect: 'tense',
  future: 'tense',
  perfect: 'tense',
  pluperfect: 'tense',
};
// NOTE: as of April 2022 there are 176 grammatical features, and 1567 lemmas
export const allFeaturesApril2022 = [
  'not_address_marker',
  'not_affirmative',
  'not_associated',
  'not_attentiveness',
  'not_biased',
  'not_classified',
  'not_complete',
  'not_contrastive',
  'not_depicted',
  'not_described',
  'not_development',
  'not_differentiated',
  'not_direct_address',
  'not_directional',
  'not_directive',
  'not_disjunctive',
  'not_distributed',
  'not_elemental',
  'not_expective',
  'not_explicit_subject',
  'not_extreme',
  'not_feminine',
  'not_gendered',
  'not_generalized',
  'not_idiomatic_article',
  'not_indefinite_relative',
  'not_inferential',
  'not_integrated_subordinate',
  'not_integrated_topic',
  'not_interactant',
  'not_interjection',
  'not_invoked_base_value',
  'not_multiple_moves',
  'not_named',
  'not_negative',
  'not_object_state',
  'not_objectified_event',
  'not_objectified_participant',
  'not_plural',
  'not_prepositional',
  'not_process',
  'not_progressive',
  'not_propositional',
  'not_quotation_marker',
  'not_re_expression_marker',
  'not_recipient',
  'not_reiterated',
  'not_relativized',
  'not_secondary_predication',
  'not_semiotic',
  'not_similar',
  'not_specified',
  'not_subject_state',
  'not_subordinate',
  'not_suppression_of_lexicalized_subjectivity',
  'not_temporal',
  'not_tentative',
  'not_topic',
  '(I)',
  '(II)',
  'accusative_association',
  'actualization',
  'actualization_tbd',
  'affirmative',
  'answer_to_question_as_thing',
  'associated',
  'association_as_description',
  'association_case_tbd',
  'attentiveness',
  'attentiveness_tbd',
  'base_value_tbd',
  'basic_association',
  'basic_depiction',
  'basic_description',
  'basic_entity',
  'basic_thing',
  'biased',
  'causality_tbd',
  'classified',
  'co-textual_expression',
  'complete',
  'completeness_tbd',
  'contemplation_tbd',
  'contemplative',
  'dative_association',
  'depicted',
  'depiction_as_description',
  'depiction_domain_tbd',
  'described',
  'description_as_depiction',
  'description_domain_tbd',
  'development',
  'differentiated',
  'direct_address',
  'direction_tbd',
  'directional',
  'directive',
  'disjunctive',
  'distributed',
  'doing',
  'elemental',
  'elided_as_accessible',
  'event_as_description',
  'event_as_thing',
  'exception',
  'exclusive',
  'expectation_tbd',
  'expective',
  'explicit_subject',
  'expression',
  'extreme',
  'far',
  'feminine',
  'from_object',
  'GBI_error',
  'gendered',
  'generalized',
  'genitive_association',
  'happening',
  'idiomatic_article',
  'indefinite_relative',
  'inferential',
  'integrated_subordinate',
  'interactant',
  'interactant_subject',
  'interjection',
  'internal_orientation',
  'invocation_of_others',
  'invoked_base_value',
  'likely_inference',
  'linguistic_token_as_thing',
  'logical_set',
  'meaning',
  'measurement',
  'multiple_expressions',
  'named',
  'near',
  'object_case_tbd',
  'objectified_by_subject',
  'objectified_by_third_party',
  'objectified_event',
  'objectified_participant',
  'objectified_temporal_predication_as_entity',
  'orientation_shift_tbd',
  'orientation_tbd',
  'participant_in_proposition_as_thing',
  'plural',
  'prepositional',
  'process',
  'progressive',
  'proposition_marker',
  'propositional',
  'propositional_association',
  'quality_delicacy_tbd',
  'quantification',
  'quotation_marker',
  'recipient',
  'reiterated',
  'relativization_as_development',
  'relativized',
  'secondary_predication',
  'semiotic',
  'speaker_excluded',
  'speaker_included',
  'speaker_shift_tbd',
  'specified',
  'speech_act',
  'subject_involvement_tbd',
  'subject_number_tbd',
  'subject_state',
  'subordinate',
  'subtractive',
  'suppression_of_lexicalized_subjectivity',
  'temporal',
  'tentative',
  'topic',
  'towards_object',
  'unlikely_inference',
  'XSL_error',
  'Ἀαρών',
  'Ἀβιά',
  'Ἀβιληνή',
  'Ἀβιούδ',
  'Ἀβραάμ',
  'ἄβυσσος',
  'ἀγαλλιάω',
  'ἀγανακτέω',
  'ἀγαπάω',
  'ἀγγαρεύω',
  'ἀγγέλλω',
  'ἄγγελος',
  'ἀγέλη',
  'ἀγκάλη',
  'ἁγνίζω',
  'ἀγνοέω',
  'ἀγορά',
  'ἀγοράζω',
  'ἄγρα',
  'ἀγραυλέω',
  'ἀγρεύω',
  'ἀγρός',
  'ἀγρυπνέω',
  'ἄγω',
  'ἀγωνία',
  'Ἀδάμ',
  'Ἀδδί',
  'ἀδελφή',
  'ἀδελφός',
  'ἀδημονέω',
  'ᾅδης',
  'ἀδμίν',
  'Ἀζώρ',
  'ἀθετέω',
  'ἀθροίζω',
  'αἰγιαλός',
  'Αἴγυπτος',
  'αἷμα',
  'αἱμορροέω',
  'αἰνέω',
  'αἶνος',
  'Αἰνών',
  'αἴρω',
  'αἰσθάνομαι',
  'αἰτέω',
  'αἴτημα',
  'αἰτία',
  'αἰών',
  'ἄκανθα',
  'ἀκοή',
  'ἀκολουθέω',
  'ἀκούω',
  'ἀκριβόω',
  'ἀκρίς',
  'ἀλάβαστρος',
  'ἀλαλάζω',
  'ἀλείφω',
  'ἀλέκτωρ',
  'Ἀλέξανδρος',
  'ἄλευρον',
  'ἀλήθεια',
  'ἁλιεύς',
  'ἀλόη',
  'ἅλυσις',
  'Ἁλφαῖος',
  'ἁμαρτία',
  'Ἀμιναδάβ',
  'ἀμπελουργός',
  'ἀμπελών',
  'ἀμφιβάλλω',
  'ἀμφίβληστρον',
  'ἄμφοδον',
  'Ἀμώς',
  'ἀναβαίνω',
  'ἀναβλέπω',
  'ἀναβοάω',
  'ἀναγινώσκω',
  'ἀναγκάζω',
  'ἀνάγω',
  'ἀναδείκνυμι',
  'ἀνάδειξις',
  'ἀναζητέω',
  'ἀναθεματίζω',
  'ἀνάθημα',
  'ἀναιρέω',
  'ἀνακαθίζω',
  'ἀνακάμπτω',
  'ἀνάκειμαι',
  'ἀνακλίνω',
  'ἀνακράζω',
  'ἀνακυλίω',
  'ἀνακύπτω',
  'ἀνάλημψις',
  'ἀναμιμνῄσκω',
  'ἀναπέμπω',
  'ἀναπηδάω',
  'ἀναπίπτω',
  'ἀναπληρόω',
  'ἀνασείω',
  'ἀνάστασις',
  'ἀναστενάζω',
  'ἀνατάσσομαι',
  'ἀνατέλλω',
  'ἀνατολή',
  'ἀνατρέπω',
  'ἀναφαίνω',
  'ἀναφέρω',
  'ἀναφωνέω',
  'ἀναχωρέω',
  'Ἀνδρέας',
  'ἄνεμος',
  'ἀνέρχομαι',
  'ἀνευρίσκω',
  'ἀνήρ',
  'ἀνθομολογέομαι',
  'ἀνθρακιά',
  'ἄνθρωπος',
  'ἀνίστημι',
  'Ἅννα',
  'Ἅννας',
  'ἄνοια',
  'ἀνοίγω',
  'ἀνορθόω',
  'ἀνταποκρίνομαι',
  'ἀντίκειμαι',
  'ἀντιλέγω',
  'ἀντλέω',
  'ἀπαγγέλλω',
  'ἀπάγχω',
  'ἀπάγω',
  'ἀπαντάω',
  'ἀπαρνέομαι',
  'ἀπάτη',
  'ἀπέρχομαι',
  'ἀπέχω',
  'ἀπιστέω',
  'ἀπιστία',
  'ἀπό',
  'ἀποβαίνω',
  'ἀποβάλλω',
  'ἀπογραφή',
  'ἀπογράφω',
  'ἀποδεκατεύω',
  'ἀποδέχομαι',
  'ἀποδημέω',
  'ἀποδίδωμι',
  'ἀποδοκιμάζω',
  'ἀποθνῄσκω',
  'ἀποκαθιστάνω',
  'ἀποκαλύπτω',
  'ἀποκεφαλίζω',
  'ἀποκόπτω',
  'ἀποκρίνομαι',
  'ἀπόκρισις',
  'ἀποκτείνω',
  'ἀποκυλίω',
  'ἀπολαμβάνω',
  'ἀπόλλυμι',
  'ἀπολύω',
  'ἀπονίζω',
  'ἀποπνίγω',
  'ἀπορέω',
  'ἀποσπάω',
  'ἀποστεγάζω',
  'ἀποστέλλω',
  'ἀπόστολος',
  'ἀποστοματίζω',
  'ἀποτάσσω',
  'ἀποτίθημι',
  'ἀποφέρω',
  'ἅπτω',
  'Ἀράμ',
  'ἀργύριον',
  'ἀρέσκω',
  'ἀριθμός',
  'Ἀριμαθαία',
  'Ἁριμαθαία',
  'ἀριστάω',
  'ἄριστον',
  'ἀρνέομαι',
  'Ἀρνί',
  'ἁρπάζω',
  'ἄρτος',
  'Ἀρφαξάδ',
  'Ἀρχέλαος',
  'ἀρχή',
  'ἀρχιερεύς',
  'ἀρχισυνάγωγος',
  'ἀρχιτελώνης',
  'ἀρχιτρίκλινος',
  'ἄρχω',
  'ἄρχων',
  'ἄρωμα',
  'Ἀσάφ',
  'ἀσέλγεια',
  'Ἀσήρ',
  'ἀσθένεια',
  'ἀσθενέω',
  'ἀσκός',
  'ἀσπάζομαι',
  'ἀσπασμός',
  'ἀστήρ',
  'ἀστραπή',
  'ἀστράπτω',
  'ἀσφάλεια',
  'ἀσφαλίζω',
  'ἀτενίζω',
  'ἀτιμάζω',
  'Αὐγοῦστος',
  'αὐλή',
  'αὐλητής',
  'αὐλίζομαι',
  'αὐξάνω',
  'αὐτόπτης',
  'αὐτός',
  'ἀφαιρέω',
  'ἄφεσις',
  'ἀφίημι',
  'ἀφίστημι',
  'ἀφρίζω',
  'ἀφροσύνη',
  'ἀφυπνόω',
  'Ἀχάζ',
  'Ἀχίμ',
  'Βαβυλών',
  'βαθύνω',
  'βάϊον',
  'βάλλω',
  'βαπτίζω',
  'βάπτισμα',
  'βαπτισμός',
  'βαπτιστής',
  'βάπτω',
  'Βαραββᾶς',
  'βαρέω',
  'Βαρθολομαῖος',
  'Βαρτιμαῖος',
  'βασανίζω',
  'βάσανος',
  'βασιλεία',
  'βασιλεύς',
  'βασιλεύω',
  'βαστάζω',
  'βάτος',
  'Βεελζεβούλ',
  'Βηθανία',
  'Βηθζαθά',
  'Βηθλέεμ',
  'Βηθσαϊδά',
  'Βηθφαγή',
  'βῆμα',
  'βιβλίον',
  'βίβλος',
  'βιβρώσκω',
  'βλάπτω',
  'βλασφημέω',
  'βλασφημία',
  'βλέπω',
  'Βοανηργές',
  'βοάω',
  'Βόες',
  'βόθυνος',
  'βολή',
  'βόσκω',
  'βουλευτής',
  'βουλεύω',
  'βουλή',
  'βούλομαι',
  'βοῦς',
  'βραχίων',
  'βρέφος',
  'βρέχω',
  'βροντή',
  'βρῶμα',
  'βυθίζω',
  'Γαββαθά',
  'Γαβριήλ',
  'γαζοφυλάκιον',
  'γαλήνη',
  'Γαλιλαία',
  'Γαλιλαῖος',
  'γαμέω',
  'γάμος',
  'γαστήρ',
  'Γεθσημανί',
  'γείτων',
  'γεμίζω',
  'γενεά',
  'γενέσια',
  'γένεσις',
  'γενετή',
  'γεννάω',
  'Γεννησαρέτ',
  'γένος',
  'Γερασηνός',
  'γεύομαι',
  'γεωργός',
  'γῆ',
  'γίνομαι',
  'γινώσκω',
  'γλῶσσα',
  'γλωσσόκομον',
  'γναφεύς',
  'γνωρίζω',
  'γογγύζω',
  'γογγυσμός',
  'Γολγοθᾶ',
  'γονεύς',
  'γόνυ',
  'γονυπετέω',
  'γραμματεύς',
  'γραφή',
  'γράφω',
  'γυνή',
  'δαιμονίζομαι',
  'δαιμόνιον',
  'δαίμων',
  'δάκρυον',
  'δακρύω',
  'δάκτυλος',
  'Δαλμανουθά',
  'δαμάζω',
  'δαπανάω',
  'Δαυίδ',
  'δέησις',
  'δεῖ',
  'δειγματίζω',
  'δείκνυμι',
  'δειπνέω',
  'δεῖπνον',
  'Δεκάπολις',
  'δένδρον',
  'δέομαι',
  'δέρω',
  'δεσμεύω',
  'δέσμιος',
  'δεσμός',
  'δεσμωτήριον',
  'δέχομαι',
  'δέω',
  'δηνάριον',
  'διαβλέπω',
  'διαγίνομαι',
  'διαγογγύζω',
  'διαγρηγορέω',
  'διαδίδωμι',
  'διαζώννυμι',
  'διακονέω',
  'διακονία',
  'διάκονος',
  'διακωλύω',
  'διαλαλέω',
  'διαλέγομαι',
  'διαλογίζομαι',
  'διαλογισμός',
  'διαμένω',
  'διαμερίζω',
  'διανεύω',
  'διανόημα',
  'διανοίγω',
  'διανυκτερεύω',
  'διαπεράω',
  'διαπορεύομαι',
  'διαπορέω',
  'διαρρήγνυμι',
  'διασκορπίζω',
  'διασπάω',
  'διαστέλλω',
  'διασῴζω',
  'διαταράσσω',
  'διατάσσω',
  'διατηρέω',
  'διατρίβω',
  'διαφέρω',
  'διαφημίζω',
  'διαχωρίζω',
  'διδάσκαλος',
  'διδάσκω',
  'διδαχή',
  'δίδραχμον',
  'Δίδυμος',
  'δίδωμι',
  'διεγείρω',
  'διερμηνεύω',
  'διέρχομαι',
  'διηγέομαι',
  'διήγησις',
  'διΐστημι',
  'διϊσχυρίζομαι',
  'δικαιόω',
  'δικαίωμα',
  'δίκτυον',
  'διοδεύω',
  'διστάζω',
  'διωγμός',
  'διώκω',
  'δόγμα',
  'δοκέω',
  'δοκός',
  'δόλος',
  'δόξα',
  'δοξάζω',
  'δοῦλος',
  'δοχή',
  'δύναμαι',
  'δύναμις',
  'δύνω',
  'δύσις',
  'δῶμα',
  'δωρέομαι',
  'δῶρον',
  'ἐάω',
  'Ἔβερ',
  'ἐγγίζω',
  'ἐγείρω',
  'ἔγερσις',
  'ἐγκαίνια',
  'ἐγκακέω',
  'ἐγκρύπτω',
  'ἔγκυος',
  'Ἑζεκίας',
  'ἐθίζω',
  'ἔθνος',
  'ἔθος',
  'εἰδέα',
  'εἶδος',
  'εἶπον',
  'εἰρήνη',
  'εἰς',
  'εἷς',
  'εἰσάγω',
  'εἰσέρχομαι',
  'εἰσπορεύομαι',
  'εἰσφέρω',
  'εἴωθα',
  'ἑκατοντάρχης',
  'ἐκβάλλω',
  'ἐκδέχομαι',
  'ἐκδίδωμι',
  'ἐκδύω',
  'ἐκεῖ',
  'ἐκεῖνος',
  'ἐκθαμβέω',
  'ἐκθαυμάζω',
  'ἐκκομίζω',
  'ἐκκρεμάννυμι',
  'ἐκλέγω',
  'ἐκλείπω',
  'ἐκμάσσω',
  'ἐκμυκτηρίζω',
  'ἐκνεύω',
  'ἐκπειράζω',
  'ἐκπλήσσω',
  'ἐκπνέω',
  'ἐκπορεύομαι',
  'ἔκστασις',
  'ἐκτείνω',
  'ἐκφέρω',
  'ἐκφεύγω',
  'ἐκχέω',
  'ἐλαία',
  'ἔλαιον',
  'ἐλαύνω',
  'Ἐλεάζαρ',
  'ἐλέγχω',
  'ἔλεος',
  'Ἐλιακίμ',
  'Ἐλιέζερ',
  'Ἐλιούδ',
  'Ἐλισάβετ',
  'ἕλκω',
  'Ἕλλην',
  'Ἑλληνίς',
  'Ἐλμαδάμ',
  'ἐλπίζω',
  'ἐμβαίνω',
  'ἐμβλέπω',
  'ἐμβριμάομαι',
  'Ἐμμαοῦς',
  'ἐμπαίζω',
  'ἐμπίπλημι',
  'ἐμπίπτω',
  'ἐμπτύω',
  'ἐμφανίζω',
  'ἐμφυσάω',
  'ἐν',
  'ἐναγκαλίζομαι',
  'ἔναντι',
  'ἐνδιδύσκω',
  'ἔνδυμα',
  'ἐνδύω',
  'ἐνεδρεύω',
  'ἐνειλέω',
  'ἐνεργέω',
  'ἐνέχω',
  'ἐνθυμέομαι',
  'ἐνθύμησις',
  'ἐνιαυτός',
  'ἐνισχύω',
  'ἐννεύω',
  'ἐνοχλέω',
  'ἐνταφιάζω',
  'ἐντέλλομαι',
  'ἐντολή',
  'ἐντυλίσσω',
  'Ἐνώς',
  'Ἑνώχ',
  'ἐξαγγέλλω',
  'ἐξάγω',
  'ἐξαποστέλλω',
  'ἐξαστράπτω',
  'ἐξέρχομαι',
  'ἔξεστι(ν)',
  'ἐξετάζω',
  'ἐξηγέομαι',
  'ἑξῆς',
  'ἐξίστημι',
  'ἔξοδος',
  'ἐξομολογέω',
  'ἐξορύσσω',
  'ἐξουθενέω',
  'ἐξουσία',
  'ἑορτή',
  'ἐπαγγέλλομαι',
  'ἐπαθροίζω',
  'ἐπαίρω',
  'ἐπαιτέω',
  'ἐπανάγω',
  'ἐπεῖδον',
  'ἐπεισελεύσεται',
  'ἐπενδύτης',
  'ἐπερωτάω',
  'ἐπέχω',
  'ἐπιβάλλω',
  'ἐπιβιβάζω',
  'ἐπίβλημα',
  'ἐπιγινώσκω',
  'ἐπιγραφή',
  'ἐπιγράφω',
  'ἐπιδείκνυμι',
  'ἐπιδίδωμι',
  'ἐπιζητέω',
  'ἐπικαθίζω',
  'ἐπίκειμαι',
  'ἐπικρίνω',
  'ἐπιλαμβάνομαι',
  'ἐπιλανθάνομαι',
  'ἐπιλέγω',
  'ἐπιλύω',
  'ἐπιμένω',
  'ἐπιπίπτω',
  'ἐπιπορεύομαι',
  'ἐπιρίπτω',
  'ἐπισκέπτομαι',
  'ἐπισκιάζω',
  'ἐπιστρέφω',
  'ἐπισυνάγω',
  'ἐπισυντρέχω',
  'ἐπισχύω',
  'ἐπιτάσσω',
  'ἐπιτίθημι',
  'ἐπιτιμάω',
  'ἐπιτρέπω',
  'ἐπίτροπος',
  'ἐπιφωνέω',
  'ἐπιφώσκω',
  'ἐπιχειρέω',
  'ἐργάζομαι',
  'ἔργον',
  'ἐρημία',
  'ἔρχομαι',
  'ἐρωτάω',
  'ἐσθής',
  'ἐσθίω',
  'Ἑσλί',
  'Ἑσρώμ',
  'ἑτοιμάζω',
  'ἔτος',
  'εὐαγγελίζω',
  'εὐαγγέλιον',
  'εὐκαιρέω',
  'εὐκαιρία',
  'εὐλογέω',
  'εὑρίσκω',
  'εὐχαριστέω',
  'ἐφημερία',
  'ἐφίστημι',
  'Ἐφραίμ',
  'ἐφφαθά',
  'ἔχθρα',
  'ἔχω',
  'Ζαβουλών',
  'Ζακχαῖος',
  'Ζάρα',
  'Ζαχαρίας',
  'ζάω',
  'Ζεβεδαῖος',
  'ζηλωτής',
  'ζητέω',
  'ζήτησις',
  'Ζοροβαβέλ',
  'ζύμη',
  'ζυμόω',
  'ζωή',
  'ζώνη',
  'ἡγεμονεύω',
  'ἡγεμονία',
  'ἡγεμών',
  'ἥκω',
  'Ἠλί',
  'Ἠλίας',
  'ἡλικία',
  'ἥλιος',
  'ἡμέρα',
  'Ἤρ',
  'Ἡρῴδης',
  'Ἡρῳδιανοί',
  'Ἡρῳδιάς',
  'Ἠσαΐας',
  'ἡσυχάζω',
  'ἦχος',
  'Θαδδαῖος',
  'θάλασσα',
  'Θαμάρ',
  'θαμβέω',
  'θάμβος',
  'θάνατος',
  'θανατόω',
  'θάπτω',
  'Θάρα',
  'θαυμάζω',
  'θεάομαι',
  'θέλημα',
  'θέλω',
  'θεμέλιος',
  'θεός',
  'Θεόφιλος',
  'θεραπεία',
  'θεραπεύω',
  'θερμαίνω',
  'θέρος',
  'θεωρέω',
  'θεωρία',
  'θηρεύω',
  'θηρίον',
  'θησαυρός',
  'θλίβω',
  'θλῖψις',
  'θνῄσκω',
  'θορυβέω',
  'θόρυβος',
  'θρηνέω',
  'θρίξ',
  'θρόμβος',
  'θυγάτηρ',
  'θυγάτριον',
  'θυμίαμα',
  'θυμιάω',
  'θυμός',
  'θυμόω',
  'θύρα',
  'θυρωρός',
  'θυσία',
  'θυσιαστήριον',
  'θύω',
  'Θωμᾶς',
  'Ἰάϊρος',
  'Ἰακώβ',
  'Ἰάκωβος',
  'Ἰανναί',
  'ἰάομαι',
  'Ἰάρετ',
  'ἰατρός',
  'Ἰδουμαία',
  'ἱδρώς',
  'ἱερατεία',
  'ἱερατεύω',
  'Ἰερεμίας',
  'ἱερεύς',
  'Ἰεριχώ',
  'ἱερός',
  'Ἱεροσόλυμα',
  'Ἱεροσολυμίτης',
  'Ἰεσσαί',
  'Ἰεχονίας',
  'Ἰησοῦς',
  'ἱματίζω',
  'ἱμάτιον',
  'ἱματισμός',
  'Ἰορδάνης',
  'Ἰουδαία',
  'Ἰούδας',
  'Ἰσαάκ',
  'Ἰσκαριώθ',
  'Ἰσραήλ',
  'ἵστημι',
  'ἰσχύω',
  'ἰχθύδιον',
  'ἰχθύς',
  'Ἰωαθάμ',
  'Ἰωανάν',
  'Ἰωάννα',
  'Ἰωάννης',
  'Ἰωβήδ',
  'Ἰωδά',
  'Ἰωνάμ',
  'Ἰωράμ',
  'Ἰωρίμ',
  'Ἰωσαφάτ',
  'Ἰωσῆς',
  'Ἰωσήφ',
  'Ἰωσήχ',
  'Ἰωσίας',
  'καθαιρέω',
  'καθαρίζω',
  'καθαρισμός',
  'καθέδρα',
  'καθέζομαι',
  'καθεύδω',
  'κάθημαι',
  'καθίζω',
  'καθίημι',
  'Καϊάφας',
  'Καϊνάμ',
  'καιρός',
  'Καῖσαρ',
  'Καισάρεια',
  'κάλαμος',
  'καλέω',
  'καλύπτω',
  'κάμηλος',
  'Κανά',
  'Καναναῖος',
  'καρδία',
  'καρπός',
  'καρποφορέω',
  'κάρφος',
  'κατά',
  'καταβαίνω',
  'κατάβασις',
  'καταγελάω',
  'κατάγνυμι',
  'κατάγω',
  'καταδιώκω',
  'καταθεματίζω',
  'καταισχύνω',
  'κατάκειμαι',
  'κατακλάω',
  'κατακλείω',
  'κατακλίνω',
  'κατακολουθέω',
  'κατακόπτω',
  'κατακρημνίζω',
  'κατακρίνω',
  'καταλαμβάνω',
  'καταλείπω',
  'καταλιθάζω',
  'κατάλυμα',
  'καταλύω',
  'κατανεύω',
  'κατανοέω',
  'καταπατέω',
  'καταπέτασμα',
  'καταπλέω',
  'καταποντίζω',
  'καταρτίζω',
  'κατασκηνόω',
  'καταστρέφω',
  'κατατίθημι',
  'καταφιλέω',
  'καταχέω',
  'κατέρχομαι',
  'κατευλογέω',
  'κατέχω',
  'κατηγορέω',
  'κατηχέω',
  'κατισχύω',
  'κατοικέω',
  'κατοίκησις',
  'Καφαρναούμ',
  'Κεδρών',
  'κεῖμαι',
  'κειρία',
  'κελεύω',
  'κεντυρίων',
  'κεραμεύς',
  'κέραμος',
  'κέρμα',
  'κερματιστής',
  'κεφαλή',
  'κῆπος',
  'κηπουρός',
  'κήρυγμα',
  'κηρύσσω',
  'κινδυνεύω',
  'κινέω',
  'κίνησις',
  'κλάδος',
  'κλαίω',
  'κλάσις',
  'κλάσμα',
  'κλάω',
  'κλείω',
  'κλέπτης',
  'κλῆρος',
  'κλίνη',
  'κλινίδιον',
  'κλίνω',
  'κλοπή',
  'κλύδων',
  'Κλωπᾶς',
  'κοδράντης',
  'κοιλία',
  'κοιμάομαι',
  'κοίμησις',
  'κοινόω',
  'κοινωνός',
  'κόκκος',
  'κολαφίζω',
  'κολλυβιστής',
  'κόλπος',
  'κολυμβήθρα',
  'κομίζω',
  'κοπάζω',
  'κοπιάω',
  'κόπτω',
  'κοράσιον',
  'κοσμέω',
  'κόσμος',
  'κοῦμ',
  'κουστωδία',
  'κόφινος',
  'κράβαττος',
  'κράζω',
  'κραιπάλη',
  'κρανίον',
  'κράσπεδον',
  'κραταιόω',
  'κρατέω',
  'κραυγάζω',
  'κραυγή',
  'κρεμάννυμι',
  'κρημνός',
  'κρίσις',
  'κρύπτω',
  'κτάομαι',
  'κτῆμα',
  'κυκλόω',
  'κύκλῳ',
  'κυλίω',
  'κῦμα',
  'κύπτω',
  'Κυρηναῖος',
  'Κυρήνιος',
  'κύριος',
  'κώμη',
  'Κωσάμ',
  'λαγχάνω',
  'Λάζαρος',
  'λαῖλαψ',
  'λαλέω',
  'λαλιά',
  'λαμβάνω',
  'Λάμεχ',
  'λαμπάς',
  'λάμπω',
  'λανθάνω',
  'λαός',
  'λατομέω',
  'λατρεύω',
  'λάχανον',
  'λεγιών',
  'λέγω',
  'λειτουργία',
  'λέντιον',
  'λέπρα',
  'λεπτός',
  'Λευί',
  'Λευίτης',
  'λευκαίνω',
  'λῆρος',
  'λῃστής',
  'λίβανος',
  'λιθάζω',
  'λίθος',
  'λίμνη',
  'λίτρα',
  'λόγος',
  'λόγχη',
  'λοιδορέω',
  'λυπέω',
  'λύπη',
  'Λυσανίας',
  'λύτρωσις',
  'λύω',
  'Μάαθ',
  'Μαγαδάν',
  'Μαγδαληνή',
  'μάγος',
  'μαθητεύω',
  'μαθητής',
  'Μαθθαῖος',
  'Μαθθάτ',
  'Μαθουσαλά',
  'μαλακία',
  'Μαλελεήλ',
  'Μάλχος',
  'Μανασσῆ',
  'Μάρθα',
  'Μαρία',
  'μαρτυρέω',
  'μαρτυρία',
  'μαρτύριον',
  'μάρτυς',
  'μαστιγόω',
  'μάστιξ',
  'Ματθάν',
  'Ματταθά',
  'Ματταθίας',
  'μάχαιρα',
  'μάχομαι',
  'μεγαλειότης',
  'μεγαλύνω',
  'μεγιστάν',
  'μεθερμηνεύω',
  'μέθη',
  'Μελεά',
  'μέλει',
  'μέλι',
  'μέλλω',
  'Μελχί',
  'Μεννά',
  'μένω',
  'μερίζω',
  'μέριμνα',
  'μέρος',
  'μεσόω',
  'Μεσσίας',
  'μετά',
  'μεταβαίνω',
  'μεταίρω',
  'μεταμέλομαι',
  'μεταμορφόω',
  'μετανοέω',
  'μετάνοια',
  'μετοικεσία',
  'μετρητής',
  'μήν',
  'μηνύω',
  'μήτηρ',
  'μήτρα',
  'μιαίνω',
  'μίγμα',
  'μίγνυμι',
  'μιμνῄσκω',
  'μισθωτός',
  'μνῆμα',
  'μνημεῖον',
  'μνηστεύω',
  'μοιχεία',
  'μοιχός',
  'μόνος',
  'μορφή',
  'μυριάς',
  'μύρον',
  'μυστήριον',
  'Μωϋσῆς',
  'Ναασσών',
  'Ναγγαί',
  'Ναζαρά',
  'Ναζωραῖος',
  'Ναθάμ',
  'Ναθαναήλ',
  'Ναΐν',
  'ναός',
  'Ναούμ',
  'νάρδος',
  'Ναχώρ',
  'νεανίσκος',
  'νεύω',
  'νεφέλη',
  'Νεφθαλίμ',
  'Νηρί',
  'νηστεία',
  'νηστεύω',
  'Νικόδημος',
  'νιπτήρ',
  'νίπτω',
  'νομίζω',
  'νομοδιδάσκαλος',
  'νόμος',
  'νόσημα',
  'νόσος',
  'νοῦς',
  'νυμφίος',
  'νύξ',
  'νύσσω',
  'Νῶε',
  'ξέστης',
  'ξηραίνω',
  'ξύλον',
  'ὁ',
  'ὄγδοος',
  'ὁδηγέω',
  'ὁδοιπορία',
  'ὁδός',
  'Ὀζίας',
  'ὀθόνιον',
  'οἶδα',
  'οἰκία',
  'οἰκοδομέω',
  'οἰκοδομή',
  'οἶκος',
  'οἰκουμένη',
  'οἶνος',
  'οἴομαι',
  'ὁμιλέω',
  'ὄμμα',
  'ὀμνύω',
  'ὁμοιόω',
  'ὁμολογέω',
  'ὄναρ',
  'ὀνάριον',
  'ὀνειδίζω',
  'ὄνειδος',
  'ὄνομα',
  'ὀνομάζω',
  'ὄνος',
  'ὄξος',
  'ὅπλον',
  'ὀπτασία',
  'ὁράω',
  'ὀργή',
  'ὀρθρίζω',
  'ὄρθρος',
  'ὅριον',
  'ὅρκος',
  'ὁρμάω',
  'ὄρος',
  'ὀρχέομαι',
  'ὀσμή',
  'ὀσφῦς',
  'οὐρανός',
  'Οὐρίας',
  'οὖς',
  'οὗτος',
  'ὀφθαλμός',
  'ὀφρῦς',
  'ὄχλος',
  'ὀψάριον',
  'ὄψις',
  'παγιδεύω',
  'παγίς',
  'παιδίον',
  'παιδίσκη',
  'παῖς',
  'παίω',
  'πανουργία',
  'παρά',
  'παραβιάζομαι',
  'παραβολή',
  'παραγγέλλω',
  'παραγίνομαι',
  'παράγω',
  'παραδίδωμι',
  'παράδοσις',
  'παραιτέομαι',
  'παρακαθέζομαι',
  'παρακαλέω',
  'παρακαλύπτω',
  'παράκλησις',
  'παρακολουθέω',
  'παρακούω',
  'παρακύπτω',
  'παραλαμβάνω',
  'παραλύω',
  'παραμυθέομαι',
  'παραπορεύομαι',
  'παρασκευή',
  'παρατηρέω',
  'παρατίθημι',
  'πάρειμι',
  'παρέρχομαι',
  'παρέχω',
  'παρθενία',
  'παρθένος',
  'παρίστημι',
  'παροιμία',
  'παρρησία',
  'πάσχα',
  'πάσχω',
  'πατάσσω',
  'πατήρ',
  'πατριά',
  'πατρίς',
  'παύω',
  'πέδη',
  'πείθω',
  'πεινάω',
  'πειράζω',
  'πειρασμός',
  'πέμπω',
  'πενθερά',
  'πενθερός',
  'πενθέω',
  'περιάγω',
  'περιάπτω',
  'περιβάλλω',
  'περιβλέπω',
  'περιδέω',
  'περιέχω',
  'περικαλύπτω',
  'περικρύβω',
  'περιλάμπω',
  'περιοικέω',
  'περιπατέω',
  'περισπάω',
  'περίσσευμα',
  'περισσεύω',
  'περιστερά',
  'περιτέμνω',
  'περιτίθημι',
  'περιτρέχω',
  'περιφέρω',
  'πετεινός',
  'πέτρα',
  'Πέτρος',
  'πηγή',
  'πηλός',
  'πήρα',
  'πῆχυς',
  'πιάζω',
  'Πιλᾶτος',
  'πίμπλημι',
  'πινακίδιον',
  'πίναξ',
  'πίνω',
  'πίπτω',
  'πιστεύω',
  'πίστις',
  'πλέκω',
  'πλεονεξία',
  'πλευρά',
  'πλέω',
  'πλῆθος',
  'πλήμμυρα',
  'πληροφορέω',
  'πληρόω',
  'πλήρωμα',
  'πλοιάριον',
  'πλοῖον',
  'πλοῦτος',
  'πλύνω',
  'πνεῦμα',
  'πνέω',
  'πνίγω',
  'ποιέω',
  'ποιμήν',
  'ποίμνη',
  'πόλις',
  'πονηρία',
  'Πόντιος',
  'πορεία',
  'πορεύομαι',
  'πορνεία',
  'πορφύρα',
  'ποταμός',
  'ποτήριον',
  'ποτίζω',
  'πούς',
  'πρᾶγμα',
  'πραιτώριον',
  'πρᾶξις',
  'πρασιά',
  'πράσσω',
  'πρεσβυτέριον',
  'προάγω',
  'προαύλιον',
  'προβαίνω',
  'προβάλλω',
  'πρόβατον',
  'προβιβάζω',
  'προδότης',
  'προέρχομαι',
  'προκόπτω',
  'προσάββατον',
  'προσαίτης',
  'προσδέχομαι',
  'προσδοκάω',
  'προσέρχομαι',
  'προσευχή',
  'προσεύχομαι',
  'προσέχω',
  'προσκαλέω',
  'προσκαρτερέω',
  'προσκεφάλαιον',
  'προσκυλίω',
  'προσκυνέω',
  'προσλαμβάνω',
  'προσορμίζω',
  'προσπίπτω',
  'προσποιέω',
  'προσπορεύομαι',
  'προσρήσσω',
  'προστάσσω',
  'προστίθημι',
  'προστρέχω',
  'προσφέρω',
  'προσφωνέω',
  'πρόσωπον',
  'προτρέχω',
  'προϋπάρχω',
  'προφέρω',
  'προφητεία',
  'προφητεύω',
  'προφήτης',
  'προφῆτις',
  'προφθάνω',
  'πρύμνα',
  'πρωΐα',
  'πρωτοκλισία',
  'πτερύγιον',
  'πτοέω',
  'πτύσμα',
  'πτύσσω',
  'πτύω',
  'πτῶμα',
  'πυγμή',
  'πύλη',
  'πυλών',
  'πυνθάνομαι',
  'πῦρ',
  'πυρέσσω',
  'πυρετός',
  'πωλέω',
  'πῶλος',
  'πωρόω',
  'πώρωσις',
  'ῥαββουνί',
  'ῥάβδος',
  'Ῥαγαύ',
  'ῥαντίζω',
  'ῥαπίζω',
  'ῥάπισμα',
  'Ῥαχάβ',
  'ῥῆγμα',
  'ῥήγνυμι',
  'ῥῆμα',
  'Ῥησά',
  'ῥίζα',
  'ῥίπτω',
  'Ῥοβοάμ',
  'Ῥούθ',
  'Ῥοῦφος',
  'ῥύσις',
  'σάββατον',
  'Σαδδουκαῖος',
  'Σαδώκ',
  'σάκκος',
  'Σαλά',
  'Σαλαθιήλ',
  'Σαλείμ',
  'σαλεύω',
  'Σαλμών',
  'Σαλώμη',
  'Σαμάρεια',
  'Σαμαρίτης',
  'Σαμαρῖτις',
  'σανδάλιον',
  'σάρξ',
  'Σατανᾶς',
  'σάτον',
  'σεισμός',
  'σείω',
  'σεληνιάζομαι',
  'Σεμεΐν',
  'Σερούχ',
  'Σήθ',
  'Σήμ',
  'σημαίνω',
  'σημεῖον',
  'σιγάω',
  'Σιδών',
  'Σίμων',
  'σίναπι',
  'σινδών',
  'σιωπάω',
  'σκανδαλίζω',
  'σκάπτω',
  'σκέλος',
  'σκεῦος',
  'σκηνοπηγία',
  'σκηνόω',
  'σκιά',
  'σκιρτάω',
  'σκληροκαρδία',
  'σκοτία',
  'σκότος',
  'σκύλλω',
  'σμύρνα',
  'σμυρνίζω',
  'Σόδομα',
  'Σολομών',
  'σορός',
  'σουδάριον',
  'Σουσάννα',
  'σοφία',
  'σπαράσσω',
  'σπαργανόω',
  'σπάω',
  'σπεῖρα',
  'σπείρω',
  'σπεκουλάτωρ',
  'σπέρμα',
  'σπεύδω',
  'σπήλαιον',
  'σπλαγχνίζομαι',
  'σπόγγος',
  'σποδός',
  'σπουδή',
  'σπυρίς',
  'στάδιον',
  'στασιαστής',
  'στάσις',
  'σταυρός',
  'σταυρόω',
  'σταφυλή',
  'στάχυς',
  'στέγη',
  'στεῖρα',
  'στενάζω',
  'στέφανος',
  'στῆθος',
  'στήκω',
  'στηρίζω',
  'στιβάς',
  'στιγμή',
  'στοά',
  'στολή',
  'στόμα',
  'στράτευμα',
  'στρατεύω',
  'στρατηγός',
  'στρατιά',
  'στρατιώτης',
  'στρέφω',
  'στρωννύω',
  'στυγνάζω',
  'συγγένεια',
  'συγκάθημαι',
  'συγκαθίζω',
  'συγκαλέω',
  'συγκατατίθεμαι',
  'συγκλείω',
  'συγκύπτω',
  'συγχαίρω',
  'συγχράομαι',
  'συζητέω',
  'συκῆ',
  'συκομορέα',
  'σῦκον',
  'συλλαλέω',
  'συλλαμβάνω',
  'συλλέγω',
  'συλλογίζομαι',
  'συλλυπέω',
  'συμβαίνω',
  'συμβάλλω',
  'συμβουλεύω',
  'συμβούλιον',
  'Συμεών',
  'συμμαθητής',
  'συμπαραγίνομαι',
  'συμπίπτω',
  'συμπληρόω',
  'συμπνίγω',
  'συμπορεύομαι',
  'συμπόσιον',
  'συμφέρω',
  'συμφωνέω',
  'συνάγω',
  'συναγωγή',
  'συνακολουθέω',
  'συναναβαίνω',
  'συνανάκειμαι',
  'συναντάω',
  'συναρπάζω',
  'συνέδριον',
  'συνείδησις',
  'σύνειμι',
  'συνεισέρχομαι',
  'συνέρχομαι',
  'συνεσθίω',
  'σύνεσις',
  'συνέχω',
  'συνθλίβω',
  'συνίημι',
  'συνίστημι',
  'συνοδία',
  'συντάσσω',
  'συντελέω',
  'συντηρέω',
  'συντίθημι',
  'συντρέχω',
  'συντρίβω',
  'συντυγχάνω',
  'Συρία',
  'Συροφοινίκισσα',
  'σύρω',
  'συσπαράσσω',
  'σύσσημον',
  'συσταυρόω',
  'συστρέφω',
  'Συχάρ',
  'σφραγίζω',
  'σχίζω',
  'σχίσμα',
  'σχοινίον',
  'σῴζω',
  'σῶμα',
  'σωτήρ',
  'σωτηρία',
  'σωφρονέω',
  'ταλιθά',
  'τάξις',
  'ταράσσω',
  'ταραχή',
  'τάσσω',
  'ταφή',
  'τάφος',
  'τέκνον',
  'τελειόω',
  'τελευτάω',
  'τελευτή',
  'τελέω',
  'τέλος',
  'τελώνης',
  'τελώνιον',
  'τετρααρχέω',
  'τετραάρχης',
  'τηρέω',
  'Τιβεριάς',
  'Τιβέριος',
  'τίθημι',
  'τίκτω',
  'τίλλω',
  'Τιμαῖος',
  'τιμή',
  'τὶς',
  'τίτλος',
  'τολμάω',
  'τόπος',
  'τράπεζα',
  'τραυματίζω',
  'Τραχωνῖτις',
  'τρεῖς',
  'τρέμω',
  'τρέφω',
  'τρέχω',
  'τρόμος',
  'τροφή',
  'τρυγάω',
  'τύπτω',
  'Τύρος',
  'ὑγιαίνω',
  'ὑδρία',
  'ὕδωρ',
  'υἱός',
  'ὑμνέω',
  'ὑπάγω',
  'ὑπαντάω',
  'ὑπάντησις',
  'ὑπάρχω',
  'ὑπερηφανία',
  'ὑπηρέτης',
  'ὕπνος',
  'ὑποδείκνυμι',
  'ὑποδέχομαι',
  'ὑποδέω',
  'ὑποκρίνομαι',
  'ὑπόκρισις',
  'ὑποκριτής',
  'ὑπολαμβάνω',
  'ὑπομένω',
  'ὑπομιμνῄσκω',
  'ὑποστρέφω',
  'ὑποστρωννύω',
  'ὑποτάσσω',
  'ὑποχωρέω',
  'ὕσσωπος',
  'ὑστερέω',
  'ὕψος',
  'ὑψόω',
  'φαίνω',
  'Φάλεκ',
  'φανερόω',
  'φανός',
  'Φανουήλ',
  'φάντασμα',
  'Φάρες',
  'Φαρισαῖος',
  'φάτνη',
  'φέρω',
  'φεύγω',
  'φήμη',
  'φημί',
  'φθόνος',
  'φιλέω',
  'Φίλιππος',
  'φιλονεικία',
  'φιμόω',
  'φοβέω',
  'φόβος',
  'φοῖνιξ',
  'φόνος',
  'φορέω',
  'φραγέλλιον',
  'φραγελλόω',
  'φυλακή',
  'φυλάσσω',
  'φυλή',
  'φύλλον',
  'φυτεύω',
  'φωνέω',
  'φωνή',
  'φῶς',
  'φωτίζω',
  'χαίρω',
  'χαλάω',
  'χαλκίον',
  'χαλκός',
  'χαρά',
  'χαρίζομαι',
  'χάρις',
  'χείμαρρος',
  'χειμών',
  'χείρ',
  'χῆρος',
  'χιλίαρχος',
  'χιτών',
  'χιών',
  'χλαμύς',
  'χοῖρος',
  'χολή',
  'Χοραζίν',
  'χορτάζω',
  'χόρτος',
  'Χουζᾶς',
  'χρεία',
  'χρηματίζω',
  'Χριστός',
  'χρονίζω',
  'χρόνος',
  'χρυσός',
  'χώρα',
  'χωρέω',
  'χωρίον',
  'ψευδομαρτυρέω',
  'ψευδομαρτυρία',
  'ψευδόμαρτυς',
  'ψῦχος',
  'ψωμίον',
  'ψώχω',
  'ὥρα',
  'ὠτάριον',
  'ὠτίον',
  'ὠφελέω',
];

export const systemLookupByFeatureApril2022 = {
  actualization_tbd: 'actualization',
  actualization: 'actualization',
  not_enclitic: 'addition_expression',
  enclitic: 'addition_expression',
  not_progressive_addition: 'addition_type',
  progressive_addition: 'addition_type',
  not_address_marker: 'address_marking',
  address_marker: 'address_marking',
  not_affirmative: 'affirmation',
  affirmative: 'affirmation',
  accusative_association: 'association_case',
  association_case_tbd: 'association_case',
  dative_association: 'association_case',
  genitive_association: 'association_case',
  basic_association: 'association_derivation',
  propositional_association: 'association_derivation',
  not_associated: 'association',
  associated: 'association',
  not_attentiveness: 'attentiveness',
  attentiveness_tbd: 'attentiveness',
  attentiveness: 'attentiveness',
  not_invoked_base_value: 'base_value',
  base_value_tbd: 'base_value',
  invoked_base_value: 'base_value',
  not_biased: 'bias',
  biased: 'bias',
  causality_tbd: 'causality',
  doing: 'causality',
  happening: 'causality',
  not_classified: 'classification',
  classified: 'classification',
  elided_as_accessible: 'co-textual_expression_type',
  co_textual_expression: 'co-textual_expression',
  not_complete: 'completeness',
  complete: 'completeness',
  completeness_tbd: 'completeness',
  contemplation_tbd: 'contemplation',
  contemplative: 'contemplation',
  not_contrastive: 'contrast',
  not_generalized: 'definition',
  generalized: 'definition',
  basic_depiction: 'depiction_derivation',
  description_as_depiction: 'depiction_derivation',
  depiction_domain_tbd: 'depiction_domain',
  not_depicted: 'depiction',
  depicted: 'depiction',
  association_as_description: 'description_derivation',
  basic_description: 'description_derivation',
  depiction_as_description: 'description_derivation',
  event_as_description: 'description_derivation',
  description_domain_tbd: 'description_domain',
  measurement: 'description_domain',
  quantification: 'description_domain',
  not_described: 'description',
  described: 'description',
  basic_development: 'development_derivation',
  logical_operation_as_development: 'development_derivation',
  relativization_as_development: 'development_derivation',
  not_development: 'development',
  development: 'development',
  not_differentiated: 'differentiation',
  differentiated: 'differentiation',
  not_direct_address: 'direct_address',
  direct_address: 'direct_address',
  not_directive: 'direction',
  direction_tbd: 'direction',
  directive: 'direction',
  not_distributed: 'distribution',
  distributed: 'distribution',
  not_double_negation: 'double_negation',
  basic_entity: 'entity_derivation',
  objectified_temporal_predication_as_entity: 'entity_derivation',
  exclusive: 'exclusivity',
  not_expective: 'expectation',
  expectation_tbd: 'expectation',
  expective: 'expectation',
  not_gendered: 'gender',
  gender_tbd: 'gender',
  gendered: 'gender',
  not_feminine: 'gendered_type',
  feminine: 'gendered_type',
  not_disjunctive: 'grouping',
  disjunctive: 'grouping',
  likely_inference: 'inference_type',
  unlikely_inference: 'inference_type',
  not_inferential: 'inferential_status',
  inferential: 'inferential_status',
  not_extreme: 'intensity',
  extreme: 'intensity',
  phatic: 'interjection_type',
  interjection_type_tbd: 'interjection',
  not_interjection: 'interjection',
  interjection: 'interjection',
  not_invocation_of_others: 'interrelation',
  invocation_of_others: 'interrelation',
  not_elemental: 'interrogation',
  elemental: 'interrogation',
  logical_set: 'logical_complexity',
  not_multiple_moves: 'move_making',
  multiple_moves: 'move_making',
  not_progressive: 'move_type',
  progressive: 'move_type',
  not_named: 'naming',
  named: 'naming',
  not_idiomatic_article: 'near_expression',
  idiomatic_article: 'near_expression',
  not_negative: 'negation',
  negative: 'negation',
  not_negated_actual: 'negative_type',
  negated_actual: 'negative_type',
  not_plural: 'number',
  number_tbd: 'number',
  plural: 'number',
  not_directional: 'object_case',
  directional: 'object_case',
  object_case_tbd: 'object_case',
  from_object: 'object_direction',
  towards_object: 'object_direction',
  not_object_state: 'object_state',
  not_suppression_of_lexicalized_subjectivity: 'objectification_type',
  suppression_of_lexicalized_subjectivity: 'objectification_type',
  objectified_by_subject: 'objectification',
  objectified_by_third_party: 'objectification',
  not_semiotic: 'order_of_experience',
  semiotic: 'order_of_experience',
  orientation_shift_tbd: 'orientation_shift',
  internal_orientation: 'orientation',
  orientation_tbd: 'orientation',
  speaker_excluded: 'person',
  speaker_included: 'person',
  not_temporal: 'predication_type',
  temporal: 'predication_type',
  not_prepositional: 'prepositional_marking',
  prepositional: 'prepositional_marking',
  not_process: 'process_domain',
  process: 'process_domain',
  speech_act: 'progressive_move_type',
  proposition_marker: 'proposition_marking',
  far: 'proximity',
  near: 'proximity',
  quality_delicacy_tbd: 'quality_delicacy',
  not_quotation_marker: 'quotation_marking',
  quotation_marker: 'quotation_marking',
  not_re_expression_marker: 're_expression_marking',
  re_expression_marker: 're_expression_marking',
  multiple_expressions: 're_expression',
  not_recipient: 'reception',
  recipient: 'reception',
  not_reiterated: 'reiteration',
  reiterated: 'reiteration',
  not_subtractive: 'relation_to_others',
  subtractive: 'relation_to_others',
  not_indefinite_relative: 'relative_definiteness',
  indefinite_relative: 'relative_definiteness',
  not_relativized: 'relativization',
  relativized: 'relativization',
  not_objectified_event: 'secondary_event',
  objectified_event: 'secondary_event',
  not_secondary_predication: 'secondary_predication',
  secondary_predication: 'secondary_predication',
  expression: 'semiosis_type',
  meaning: 'semiosis_type',
  not_similar: 'similarity',
  mainline: 'situational_progression_type',
  offline: 'situational_progression_type',
  speaker_shift_tbd: 'speaker_shift',
  not_specified: 'specification',
  specified: 'specification',
  not_propositional: 'speech_act_type',
  propositional: 'speech_act_type',
  not_interactant: 'speech_role',
  interactant: 'speech_role',
  not_explicit_subject: 'subject_construal',
  explicit_subject: 'subject_construal',
  interactant_subject: 'subject_involvement',
  subject_involvement_tbd: 'subject_involvement',
  subject_number_tbd: 'subject_number',
  not_subject_state: 'subject_state',
  subject_state: 'subject_state',
  not_integrated_subordinate: 'subordinate_type',
  integrated_subordinate: 'subordinate_type',
  not_subordinate: 'subordination',
  subordinate: 'subordination',
  not_exception: 'subtraction_type',
  exception: 'subtraction_type',
  not_tentative: 'tentativeness',
  tentative: 'tentativeness',
  answer_to_question_as_thing: 'thing_derivation',
  basic_thing: 'thing_derivation',
  event_as_thing: 'thing_derivation',
  linguistic_token_as_thing: 'thing_derivation',
  participant_in_proposition_as_thing: 'thing_derivation',
  not_integrated_topic: 'topic_type',
  not_topic: 'topicalization',
  topic: 'topicalization',
  not_objectified_participant: 'transitivity',
  objectified_participant: 'transitivity',
};
