export const systemGroups = {
  moveSystems: ['move_recursion'],

  actSystems: [
    'act_tentativeness',
    'act_recursion',
    'act_progression',
    'act_type',
    'act_sequencing',
    'direction',
    'contemplation',
    'conventionality',
    'orientation',
    'interjection',
    'expectation',
    'question_type',
    'yes_no_type',
    'bias_type',
  ],

  discourseSystems: [
    'discourse_marker_type',
    'ostentation',
    'direct_address',
    'proposition_marking',
    'operator_as_marker_type',
  ],

  otherSystems: [
    'combination_type',
    'speech_centrality',
    'instantiator_expression',
    'unit_periphery',
    'unit_grouping',
    'association_modality',
    'association_marking',
    'association_expression',
    'associated_phenomenon',
    'property_type',
    'relation_type',
    'attribute_type',
    'configuration_type',
    'textual_expression',
    'instantiator_subjectivity',
    'objective_association',
    'process_selection',
    'entity_construal',
    'interactant_indication',
    'entity_definiteness',
    'analysis_type',
    'property_mode',
    'proximity',
    'intensification',
    'association_type',
    'associated_meaning_type',
    'specific_association_type',
    'proximity_type',
    'affected_expression_type',
    'adjustment_type',
    'associated_experience_type',
    'subject_speaker_inclusion',
    'identification_type',
    'modality_assignment',
    'exclusion',
    'group_recursion',
    'normal_progression_type',
    'invoking_of_group',
    'logical_operator_type',
    'operator_expression',
    'exclusion_type',
    'pro-form_person',
    'topicalization',
    'topic_type',
    'sequence_operator_type',
    'collation_strategy',
    'recognition_criterion',
    'embedded_proposition_marking',
    'actualization',
    'diachronic_operation_type',
    'totality',
  ],

  morphologicalSystems: [
    'attentiveness',
    'completion',
    'entity_gender',
    'gendered_type',
    'entity_number',
    'subject_indication',
    'subject_number',
  ],
};

export const allChoices = [
  'configuration',
  'textually_affected_expression',
  'explicitly_interactant',
  'alternation',
  'non-enclitic_operator_root',
  'explicit_direct_address',
  'tbd',
  'explicitly_feminine',
  'associated_relation',
  'peripheral_property',
  'definite_entity',
  'category_of_similar_things',
  'offline_progression',
  'additional_integral_association',
  'associated_experience',
  'name_of_specific_thing',
  'end_act_sequence',
  'synchronic_operation',
  'no_explicit_experiential_construal',
  'explicit_proposition_marker',
  'diachronic_operation',
  'not_necessarily_directive',
  'explicitly_interactant_subject',
  'explicit_experiential_construal',
  'construed_phenomenon',
  'subjective_participant_as_instantiator',
  'not_necessarily_internal_orientation',
  'single_item',
  'elided_as_accessible',
  'not_necessarily_tentative_act',
  'maximal_attentiveness',
  'associated_meaning',
  'continue_act_sequence',
  'explicit_totality',
  'not_necessarily_feminine',
  'collation',
  'single_act',
  'explicitly_complete',
  'process_manifested_by_subjective_participant',
  'yes_no_question',
  'exclusion_of_something_actual_otherwise',
  'explicit_interjection',
  'explicit_instantiator',
  'not_necessarily_expective',
  'explicitly_internal_orientation',
  'replacement_of_earlier_members',
  'minimal_attentiveness',
  'speaker_explicitly_excluded_from_subject',
  'indefinite',
  'explicitly_ostentatious_unit',
  'invoking_of_other_group_members',
  'continue_grouping',
  'not_necessarily_plural_entity',
  'replacement',
  'no_invoking_of_other_group_members',
  'not_necessarily_interactant_subject',
  'not_necessarily_contemplative',
  'not_explicitly_excluded_from_membership',
  'end_turn',
  'temporal_relation',
  'biased_towards_denial',
  'explicitly_directive',
  'explicitly_plural_entity',
  'genitive_association',
  'not_necessarily_plural_subject',
  'dative_association',
  'attribute',
  'speech_act_as_projected_discourse',
  'speech_as_core_of_act',
  'stop_grouping',
  'set_operator_as_discourse_marker',
  'accusative_association',
  'logical_relation',
  'simple_progression',
  'redundant_actualization_marker',
  'progression_towards_completion',
  'explicitly_gendered',
  'explicitly_tentative_act',
  'more_specific_association',
  'independent',
  'no_explicit_instantiator',
  'predication',
  'construed_proposition',
  'associated_entity',
  'explicitly_biased',
  'near',
  'addition',
  'sequence_operator',
  'continue_turn',
  'intrinsic_classification',
  'explicit_proximity',
  'explicitly_expective',
  'prepositional_association_marking',
  'explicitly_contemplative',
  'explicit_intensifier',
  'process_caused_by_subjective_participant',
  'speaker_explicitly_included_in_subject',
  'not_necessarily_interactant',
  'predication_as_abstract_proposition',
  'no_explicit_proximity',
  'sequence_of_acts',
  'speaker_excluded',
  'objective_association_as_instantiator',
  'group_of_items',
  'not_necessarily_actual_otherwise',
  'instantiation_of_event',
  'association',
  'independent_modality',
  'biased_towards_assertion',
  'not_necessarily_gendered',
  'explicitly_plural_subject',
  'inventional_act',
  'extrinsic_depiction',
  'normal_expression',
  'inflectional_association_marking',
  'explicitly_excluded_from_membership',
  'not_necessarily_complete',
  'no_additional_integral_association',
  'explicit_topic',
  'explicit_discourse_progression',
];

export const allSituationalChoices = [
  'no embedded discourse',
  'excluded discourse only',
  'practical-ie-outwardly-oriented',
  'action',
  'projecting',
  'allying',
  'private',
  'monological',
  'non-institutional-or-neutralized',
  'distant',
  'ancillary',
  'addressee-more-passive',
  'spoken',
  'phonic',
  'multilogical',
  'institutional',
  'addressee-more-active',
  'conceptual-ie-internally-oriented',
  'relation',
  'instructing',
  'opposing',
  'neutral',
  'unclear',
  'asserting',
  'close',
  'dialogical',
  'constitutive',
  'disinterested',
  'written',
  'on-someones-side',
  'graphic',
  'contact',
  'equalized',
];

export const situationSystemNetwork = [
  {
    title: 'ABSTRACTNESS-TYPE-(FIELD)',
    key: 'ABSTRACTNESS-TYPE-(FIELD)',
    value: 'ABSTRACTNESS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'conceptual-ie-internally-oriented',
        key: 'conceptual-ie-internally-oriented',
        value: 'conceptual-ie-internally-oriented',
      },
      {
        title: 'practical-ie-outwardly-oriented',
        key: 'practical-ie-outwardly-oriented',
        value: 'practical-ie-outwardly-oriented',
      },
    ],
  },
  {
    title: 'ACTIVITY-FOCUS-(FIELD)',
    key: 'ACTIVITY-FOCUS-(FIELD)',
    value: 'ACTIVITY-FOCUS-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'action',
        key: 'action',
        value: 'action',
      },
      {
        title: 'relation',
        key: 'relation',
        value: 'relation',
      },
      {
        title: 'contact',
        key: 'contact',
        value: 'contact',
      },
    ],
  },
  {
    title: 'GOALS-TYPE-(FIELD)',
    key: 'GOALS-TYPE-(FIELD)',
    value: 'GOALS-TYPE-(FIELD)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'instructing',
        key: 'instructing',
        value: 'instructing',
      },
      {
        title: 'informing',
        key: 'informing',
        value: 'informing',
        children: [
          {
            title: 'INFORMING-TYPE',
            key: 'INFORMING-TYPE',
            value: 'INFORMING-TYPE',
            entryCondition: 'informing',
            children: [
              {
                title: 'projecting',
                key: 'projecting',
                value: 'projecting',
              },
              {
                title: 'asserting',
                key: 'asserting',
                value: 'asserting',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    key: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    value: 'VALUE-ORIENTATION-PREDISPOSITION-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'allying',
        key: 'allying',
        value: 'allying',
      },
      {
        title: 'opposing',
        key: 'opposing',
        value: 'opposing',
      },
    ],
  },
  {
    title: 'PUBLICITY-(TENOR)',
    key: 'PUBLICITY-(TENOR)',
    value: 'PUBLICITY-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'onlookers',
        key: 'onlookers',
        value: 'onlookers',
        children: [
          {
            title: 'ONLOOKERS-TYPE',
            key: 'ONLOOKERS-TYPE',
            value: 'ONLOOKERS-TYPE',
            entryCondition: 'onlookers',
            children: [
              {
                title: 'disinterested',
                key: 'disinterested',
                value: 'disinterested',
              },
              {
                title: 'interested',
                key: 'interested',
                value: 'interested',
                children: [
                  {
                    title: 'INTERESTED-TYPE',
                    key: 'INTERESTED-TYPE',
                    value: 'INTERESTED-TYPE',
                    entryCondition: 'interested',
                    children: [
                      {
                        title: 'neutral',
                        key: 'neutral',
                        value: 'neutral',
                      },
                      {
                        title: 'on-someones-side',
                        key: 'on-someones-side',
                        value: 'on-someones-side',
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        title: 'private',
        key: 'private',
        value: 'private',
      },
    ],
  },
  {
    title: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    key: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    value: 'NUMBER-OF-SPEAKING-PARTICIPANTS-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'monological',
        key: 'monological',
        value: 'monological',
      },
      {
        title: 'more-than-one',
        key: 'more-than-one',
        value: 'more-than-one',
        children: [
          {
            title: 'MORE-THAN-ONE-TYPE',
            key: 'MORE-THAN-ONE-TYPE',
            value: 'MORE-THAN-ONE-TYPE',
            entryCondition: 'more-than-one',
            children: [
              {
                title: 'dialogical',
                key: 'dialogical',
                value: 'dialogical',
              },
              {
                title: 'multilogical',
                key: 'multilogical',
                value: 'multilogical',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'CONTROL-TYPE-(TENOR)',
    key: 'CONTROL-TYPE-(TENOR)',
    value: 'CONTROL-TYPE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'hierarchic',
        key: 'hierarchic',
        value: 'hierarchic',
        children: [
          {
            title: 'HIERARCHIC-TYPE',
            key: 'HIERARCHIC-TYPE',
            value: 'HIERARCHIC-TYPE',
            entryCondition: 'hierarchic',
            children: [
              {
                title: 'institutional',
                key: 'institutional',
                value: 'institutional',
                gloss:
                  'at least one participant represents repercussive power structures',
              },
              {
                title: 'non-institutional-or-neutralized',
                key: 'non-institutional-or-neutralized',
                value: 'non-institutional-or-neutralized',
              },
            ],
          },
        ],
      },
      {
        title: 'non-hierarchic',
        key: 'non-hierarchic',
        value: 'non-hierarchic',
        children: [
          {
            title: 'NON-HIERARCHIC-TYPE',
            key: 'NON-HIERARCHIC-TYPE',
            value: 'NON-HIERARCHIC-TYPE',
            entryCondition: 'non-hierarchic',
            children: [
              {
                title: 'unclear',
                key: 'unclear',
                value: 'unclear',
              },
              {
                title: 'equalized',
                key: 'equalized',
                value: 'equalized',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'SOCIAL-DISTANCE-(TENOR)',
    key: 'SOCIAL-DISTANCE-(TENOR)',
    value: 'SOCIAL-DISTANCE-(TENOR)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'close',
        key: 'close',
        value: 'close',
      },
      {
        title: 'distant',
        key: 'distant',
        value: 'distant',
      },
    ],
  },
  {
    title: 'LANGUAGE-ROLE-TYPE-(MODE)',
    key: 'LANGUAGE-ROLE-TYPE-(MODE)',
    value: 'LANGUAGE-ROLE-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'constitutive',
        key: 'constitutive',
        value: 'constitutive',
      },
      {
        title: 'ancillary',
        key: 'ancillary',
        value: 'ancillary',
      },
    ],
  },
  {
    title: 'PROCESS-SHARING-TYPE-(MODE)',
    key: 'PROCESS-SHARING-TYPE-(MODE)',
    value: 'PROCESS-SHARING-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'addressee-more-active',
        key: 'addressee-more-active',
        value: 'addressee-more-active',
      },
      {
        title: 'addressee-more-passive',
        key: 'addressee-more-passive',
        value: 'addressee-more-passive',
      },
    ],
  },
  {
    title: 'CHANNEL-TYPE-(MODE)',
    key: 'CHANNEL-TYPE-(MODE)',
    value: 'CHANNEL-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'phonic',
        key: 'phonic',
        value: 'phonic',
      },
      {
        title: 'graphic',
        key: 'graphic',
        value: 'graphic',
      },
    ],
  },
  {
    title: 'MEDIUM-TYPE-(MODE)',
    key: 'MEDIUM-TYPE-(MODE)',
    value: 'MEDIUM-TYPE-(MODE)',
    entryCondition: 'contextual-configuration',
    children: [
      {
        title: 'spoken',
        key: 'spoken',
        value: 'spoken',
      },
      {
        title: 'written',
        key: 'written',
        value: 'written',
      },
    ],
  },
];

export const systemsDictionary = {
  field: {
    ABSTRACTNESS: [
      'conceptual-ie-internally-oriented',
      'practical-ie-outwardly-oriented',
    ],
    ACTIVITY_FOCUS: ['action', 'relation', 'contact'],
    GOALS: ['instructing', 'projecting', 'asserting'],
  },
  tenor: {
    VALUE_ORIENTATION_PREDISPOSITION: ['allying', 'opposing'],

    PUBLICITY: ['disinterested', 'neutral', 'on-someones-side', 'private'],
    NUMBER_OF_SPEAKING_PARTICIPANTS: [
      'monological',
      'dialogical',
      'multilogical',
    ],
    CONTROL: [
      'institutional',
      'non-institutional-or-neutralized',
      'unclear',
      'equalized',
    ],
    SOCIAL_DISTANCE: ['close', 'distant'],
  },
  mode: {
    LANGUAGE_ROLE: ['constitutive', 'ancillary'],
    PROCESS_SHARING: ['addressee-more-active', 'addressee-more-passive'],
    CHANNEL: ['phonic', 'graphic'],
    MEDIUM: ['spoken', 'written'],
  },
};
